from __future__ import annotations
import microcontroller
"""
board takayoshiotake Octave RP2040
https://circuitpython.org/boards/takayoshiotake_octave_rp2040
"""
GPIO0: microcontroller.Pin = ...
GPIO1: microcontroller.Pin = ...
GPIO2: microcontroller.Pin = ...
GPIO3: microcontroller.Pin = ...
GPIO4: microcontroller.Pin = ...
GPIO5: microcontroller.Pin = ...
GPIO6: microcontroller.Pin = ...
GPIO7: microcontroller.Pin = ...
GPIO8: microcontroller.Pin = ...
GPIO9: microcontroller.Pin = ...
GPIO10: microcontroller.Pin = ...
GPIO11: microcontroller.Pin = ...
GPIO12: microcontroller.Pin = ...
GPIO13: microcontroller.Pin = ...
GPIO14: microcontroller.Pin = ...
GPIO15: microcontroller.Pin = ...
GPIO16: microcontroller.Pin = ...
GPIO17: microcontroller.Pin = ...
GPIO18: microcontroller.Pin = ...
GPIO19: microcontroller.Pin = ...
GPIO20: microcontroller.Pin = ...
GPIO21: microcontroller.Pin = ...
GPIO22: microcontroller.Pin = ...
GPIO23: microcontroller.Pin = ...
GPIO24: microcontroller.Pin = ...
GPIO25: microcontroller.Pin = ...
GPIO26: microcontroller.Pin = ...
GPIO27: microcontroller.Pin = ...
GPIO28: microcontroller.Pin = ...
GPIO29: microcontroller.Pin = ...
ADC0: microcontroller.Pin = ...
ADC1: microcontroller.Pin = ...
ADC2: microcontroller.Pin = ...
ADC3: microcontroller.Pin = ...
NEOPIX: microcontroller.Pin = ...
NEOPIX_POWER: microcontroller.Pin = ...
