from __future__ import annotations
import busio
import microcontroller
"""
board Adafruit Industries LLC CircuitPlayground Express
https://circuitpython.org/boards/circuitplayground_express
"""
A0: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
SPEAKER: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
A6: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
A7: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
LIGHT: microcontroller.Pin = ...
A8: microcontroller.Pin = ...
TEMPERATURE: microcontroller.Pin = ...
A9: microcontroller.Pin = ...
BUTTON_A: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
BUTTON_B: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
SLIDE_SWITCH: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
REMOTEIN: microcontroller.Pin = ...
IR_RX: microcontroller.Pin = ...
REMOTEOUT: microcontroller.Pin = ...
IR_TX: microcontroller.Pin = ...
IR_PROXIMITY: microcontroller.Pin = ...
MICROPHONE_CLOCK: microcontroller.Pin = ...
MICROPHONE_DATA: microcontroller.Pin = ...
ACCELEROMETER_INTERRUPT: microcontroller.Pin = ...
ACCELEROMETER_SDA: microcontroller.Pin = ...
ACCELEROMETER_SCL: microcontroller.Pin = ...
SPEAKER_ENABLE: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

