from __future__ import annotations
import busio
import microcontroller
"""
board Boardsource BLOK
https://circuitpython.org/boards/boardsource_blok
"""
TX: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
GP02: microcontroller.Pin = ...
GP03: microcontroller.Pin = ...
GP04: microcontroller.Pin = ...
GP05: microcontroller.Pin = ...
GP06: microcontroller.Pin = ...
GP07: microcontroller.Pin = ...
GP08: microcontroller.Pin = ...
GP09: microcontroller.Pin = ...
GP10: microcontroller.Pin = ...
GP11: microcontroller.Pin = ...
GP12: microcontroller.Pin = ...
GP13: microcontroller.Pin = ...
GP14: microcontroller.Pin = ...
GP15: microcontroller.Pin = ...
GP16: microcontroller.Pin = ...
GP17: microcontroller.Pin = ...
GP18: microcontroller.Pin = ...
GP20: microcontroller.Pin = ...
GP21: microcontroller.Pin = ...
GP22: microcontroller.Pin = ...
GP23: microcontroller.Pin = ...
GP24: microcontroller.Pin = ...
GP24: microcontroller.Pin = ...
GP25: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
GP26: microcontroller.Pin = ...
GP27: microcontroller.Pin = ...
GP28: microcontroller.Pin = ...
GP29: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


