from __future__ import annotations
import microcontroller
"""
board Winterbloom Big Honking Button
https://circuitpython.org/boards/winterbloom_big_honking_button
"""
BUTTON: microcontroller.Pin = ...
HONK_OUT: microcontroller.Pin = ...
GATE_OUT: microcontroller.Pin = ...
GATE_IN: microcontroller.Pin = ...
PITCH_IN: microcontroller.Pin = ...
V5: microcontroller.Pin = ...
