from __future__ import annotations
import busio
import displayio
import microcontroller
import typing
"""
board Adafruit Industries LLC Hallowing M4 Express
https://circuitpython.org/boards/hallowing_m4_express
"""
A0: microcontroller.Pin = ...
SPEAKER: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
TOUCH1: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
TOUCH2: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
TOUCH3: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
TOUCH4: microcontroller.Pin = ...
LIGHT: microcontroller.Pin = ...
A7: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
ACCELEROMETER_INTERRUPT: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
TFT_BACKLIGHT: microcontroller.Pin = ...
TFT_CS: microcontroller.Pin = ...
TFT_DC: microcontroller.Pin = ...
TFT_RESET: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
VOLTAGE_MONITOR: microcontroller.Pin = ...
A6: microcontroller.Pin = ...
BATTERY: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
EXTERNAL_NEOPIXEL: microcontroller.Pin = ...
A9: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
SENSE: microcontroller.Pin = ...
A8: microcontroller.Pin = ...
SPEAKER_ENABLE: microcontroller.Pin = ...
CAP_PIN: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
DISPLAY: displayio.Display = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

