from __future__ import annotations
import busio
import microcontroller
import typing
"""
board Oak Development Technologies CP Sapling
https://circuitpython.org/boards/cp_sapling_m0
"""
D5: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
SS: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


