from __future__ import annotations
import busio
import microcontroller
import typing
"""
board Espressif ESP32-S2-HMI-DevKit-1
https://circuitpython.org/boards/espressif_hmi_devkit_1
"""
IO0: microcontroller.Pin = ...
IO1: microcontroller.Pin = ...
IO2: microcontroller.Pin = ...
IO3: microcontroller.Pin = ...
IO4: microcontroller.Pin = ...
IO5: microcontroller.Pin = ...
IO6: microcontroller.Pin = ...
IO7: microcontroller.Pin = ...
IO8: microcontroller.Pin = ...
IO9: microcontroller.Pin = ...
IO10: microcontroller.Pin = ...
IO11: microcontroller.Pin = ...
IO12: microcontroller.Pin = ...
IO13: microcontroller.Pin = ...
IO14: microcontroller.Pin = ...
IO15: microcontroller.Pin = ...
IO16: microcontroller.Pin = ...
IO17: microcontroller.Pin = ...
IO18: microcontroller.Pin = ...
IO19: microcontroller.Pin = ...
IO20: microcontroller.Pin = ...
IO21: microcontroller.Pin = ...
IO26: microcontroller.Pin = ...
IO33: microcontroller.Pin = ...
IO34: microcontroller.Pin = ...
IO35: microcontroller.Pin = ...
IO36: microcontroller.Pin = ...
IO37: microcontroller.Pin = ...
IO38: microcontroller.Pin = ...
IO39: microcontroller.Pin = ...
IO40: microcontroller.Pin = ...
IO41: microcontroller.Pin = ...
IO42: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
IO43: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
IO44: microcontroller.Pin = ...
IO45: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
LCD_RS: microcontroller.Pin = ...
LCD_DATA: typing.Any = ...
LCD_WR: microcontroller.Pin = ...
LCD_RS: microcontroller.Pin = ...
CS_SD: microcontroller.Pin = ...
CS_CNN: microcontroller.Pin = ...
MISO: typing.Any = ...
MOSI: typing.Any = ...
SCK: typing.Any = ...
SCL: typing.Any = ...
SDA: typing.Any = ...
CAN_TX: microcontroller.Pin = ...
CAN_RX: microcontroller.Pin = ...
MIC_ADC_M: microcontroller.Pin = ...
DAC_OUT: microcontroller.Pin = ...
AUDIO_SPI_MISO: microcontroller.Pin = ...
AUDIO_SPI_MOSI: microcontroller.Pin = ...
AUDIO_SPI_SCK: microcontroller.Pin = ...
AUDIO_SPI_CS: microcontroller.Pin = ...
AUDIO_BT_ADC: microcontroller.Pin = ...
AUDIO_SCL: microcontroller.Pin = ...
AUDIO_SDA: microcontroller.Pin = ...
AUDIO_I2S0_MCLK: microcontroller.Pin = ...
AUDIO_I2S0_BCLK: microcontroller.Pin = ...
AUDIO_I2S0_LRCK: microcontroller.Pin = ...
AUDIO_I2S0_SDI: microcontroller.Pin = ...
AUDIO_I2S0_SDO: microcontroller.Pin = ...
AUDIO_RST: microcontroller.Pin = ...
AUDIO_WAKE_INT: microcontroller.Pin = ...
AUDIO_I2S1_MCLK: microcontroller.Pin = ...
AUDIO_PA_CTRL: microcontroller.Pin = ...
AUDIO_I2S1_SDI: microcontroller.Pin = ...
AUDIO_I2S1_SDO: microcontroller.Pin = ...
AUDIO_I2S1_LRCK_DAC1: microcontroller.Pin = ...
AUDIO_I2S1_BCLK_DAC2: microcontroller.Pin = ...
def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


