from __future__ import annotations
import busio
import microcontroller
"""
board senseBox senseBox MCU
https://circuitpython.org/boards/sensebox_mcu
"""
A1: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
A6: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
UART_PWR: microcontroller.Pin = ...
TX1: microcontroller.Pin = ...
RX1: microcontroller.Pin = ...
TX2: microcontroller.Pin = ...
RX2: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
I2C_PWR: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
RED_LED: microcontroller.Pin = ...
GREEN_LED: microcontroller.Pin = ...
XB1_PWR: microcontroller.Pin = ...
XB2_PWR: microcontroller.Pin = ...
XB1_CS: microcontroller.Pin = ...
XB2_CS: microcontroller.Pin = ...
XB1_INT: microcontroller.Pin = ...
XB2_INT: microcontroller.Pin = ...
XB1_RX: microcontroller.Pin = ...
XB1_TX: microcontroller.Pin = ...
XB2_RX: microcontroller.Pin = ...
XB2_TX: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

