from __future__ import annotations
import busio
import microcontroller
import typing
"""
board Cytron Cytron Maker Feather AIoT S3
https://circuitpython.org/boards/cytron_maker_feather_aiot_s3
"""
BOOT: microcontroller.Pin = ...
BOOT0: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
L: microcontroller.Pin = ...
LED_BUILTIN: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
BUTTON: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
T4: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
T5: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
T6: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
SS: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
T7: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
A7: microcontroller.Pin = ...
T8: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
T9: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
T10: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
VP_EN: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
BUZZER: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
VIN: microcontroller.Pin = ...
VBATT: microcontroller.Pin = ...
VOLTAGE_MONITOR: microcontroller.Pin = ...
A12: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
A11: microcontroller.Pin = ...
T14: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
A10: microcontroller.Pin = ...
D15: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
A9: microcontroller.Pin = ...
D16: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
A6: microcontroller.Pin = ...
D17: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
A8: microcontroller.Pin = ...
D18: microcontroller.Pin = ...
D21: microcontroller.Pin = ...
D38: microcontroller.Pin = ...
D39: microcontroller.Pin = ...
D40: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D41: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
D42: microcontroller.Pin = ...
RGB: microcontroller.Pin = ...
RGB_BUILTIN: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
D46: microcontroller.Pin = ...
D47: microcontroller.Pin = ...
D48: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

