from __future__ import annotations
import busio
import microcontroller
import typing
"""
board Blues Inc. Swan R5
https://circuitpython.org/boards/swan_r5
"""
D0: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
CS: microcontroller.Pin = ...
RTS: microcontroller.Pin = ...
CTS: microcontroller.Pin = ...
RX0: microcontroller.Pin = ...
TX0: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
A6: microcontroller.Pin = ...
A7: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
D15: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
SCL3: microcontroller.Pin = ...
SDA3: microcontroller.Pin = ...
RX2: microcontroller.Pin = ...
RTS2: microcontroller.Pin = ...
CTS2: microcontroller.Pin = ...
TX3: microcontroller.Pin = ...
RX3: microcontroller.Pin = ...
RTS3: microcontroller.Pin = ...
CTS3: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
SCL2: microcontroller.Pin = ...
SDA2: microcontroller.Pin = ...
QEN: microcontroller.Pin = ...
QCS: microcontroller.Pin = ...
QCLK: microcontroller.Pin = ...
EN: microcontroller.Pin = ...
TX2: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
QIO3: microcontroller.Pin = ...
QIO2: microcontroller.Pin = ...
QIO1: microcontroller.Pin = ...
QIO0: microcontroller.Pin = ...
ext: typing.Any = ...
A0: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
VOLTAGE_MONITOR: microcontroller.Pin = ...
BUTTON_USR: microcontroller.Pin = ...
SWITCH: microcontroller.Pin = ...
BUTTON: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
DAC1: microcontroller.Pin = ...
DAC2: microcontroller.Pin = ...
SS: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
MICROPHONE_CLOCK: microcontroller.Pin = ...
MICROPHONE_DATA: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

