from __future__ import annotations
import busio
import displayio
import microcontroller
"""
board m5stack_core_basic
https://circuitpython.org/boards/m5stack_core_basic
"""
MOSI: microcontroller.Pin = ...
D23: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
D19: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
D18: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
RX2: microcontroller.Pin = ...
D16: microcontroller.Pin = ...
PORTC_RX: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
PORTA_SDA: microcontroller.Pin = ...
D21: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
A12: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
A15: microcontroller.Pin = ...
D15: microcontroller.Pin = ...
A35: microcontroller.Pin = ...
D35: microcontroller.Pin = ...
A36: microcontroller.Pin = ...
D36: microcontroller.Pin = ...
PORTB_IN: microcontroller.Pin = ...
A25: microcontroller.Pin = ...
D25: microcontroller.Pin = ...
SPEAKER: microcontroller.Pin = ...
A26: microcontroller.Pin = ...
D26: microcontroller.Pin = ...
PORTB_OUT: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
TX2: microcontroller.Pin = ...
D17: microcontroller.Pin = ...
PORTC_TX: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
PORTA_SCL: microcontroller.Pin = ...
D22: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
A13: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
A34: microcontroller.Pin = ...
D34: microcontroller.Pin = ...
BTN_A: microcontroller.Pin = ...
BTN_B: microcontroller.Pin = ...
BTN_C: microcontroller.Pin = ...
SD_CS: microcontroller.Pin = ...
TFT_CS: microcontroller.Pin = ...
TFT_DC: microcontroller.Pin = ...
TFT_RESET: microcontroller.Pin = ...
TFT_BACKLIGHT: microcontroller.Pin = ...
DISPLAY: displayio.Display = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

