from __future__ import annotations
import busio
import microcontroller
import typing
"""
board SparkFun Electronics Thing Plus - STM32
https://circuitpython.org/boards/sparkfun_stm32_thing_plus
"""
A0: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
CIPO: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
COPI: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
SDIO_CLOCK: microcontroller.Pin = ...
SDIO_COMMAND: microcontroller.Pin = ...
SDIO_DATA: typing.Any = ...
CAN_RX: microcontroller.Pin = ...
CAN_TX: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

