from __future__ import annotations
import busio
import microcontroller
"""
board BH Dynamics DynOSSAT-EDU-EPS-v1.0
https://circuitpython.org/boards/dynossat_edu_eps
"""
SCK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
D26: microcontroller.Pin = ...
D27: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
OVTEMP: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
SAT_RESET: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
SAT_PWR_ENABLE: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
INT_IMU_OBC: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
PWRMON_SDA: microcontroller.Pin = ...
PWRMON_SCL: microcontroller.Pin = ...
PWRMON_ALERT: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
V_3V3_MEAS: microcontroller.Pin = ...
V_5V_MEAS: microcontroller.Pin = ...
FLASH_SCK: microcontroller.Pin = ...
FLASH_MOSI: microcontroller.Pin = ...
FLASH_MISO: microcontroller.Pin = ...
FLASH_CS: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

