from __future__ import annotations
import busio
import microcontroller
"""
board Adafruit Industries LLC ProxLight Trinkey M0
https://circuitpython.org/boards/adafruit_proxlight_trinkey_m0
"""
INTERRUPT: microcontroller.Pin = ...
TOUCH2: microcontroller.Pin = ...
TOUCH1: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


