from __future__ import annotations
import busio
import microcontroller
"""
board XinaBox XinaBox CS11
https://circuitpython.org/boards/xinabox_cs11
"""
RX: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
CS: microcontroller.Pin = ...
ALERT: microcontroller.Pin = ...
RED: microcontroller.Pin = ...
GREEN: microcontroller.Pin = ...
BLUE: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

