from __future__ import annotations
import busio
import microcontroller
import typing
"""
board Benjamin Shockley Fig Pi
https://circuitpython.org/boards/bwshockley_figpi
"""
A0: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
BUTTON: microcontroller.Pin = ...
SDA1: microcontroller.Pin = ...
D18: microcontroller.Pin = ...
SCL1: microcontroller.Pin = ...
D19: microcontroller.Pin = ...
I2C0: typing.Any = ...
STEMMA_I2C0: typing.Any = ...
STEMMA_I2C1: typing.Any = ...
I2C1: typing.Any = ...
def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

