from __future__ import annotations
import displayio
import microcontroller
"""
board Raspberry Pi Compute Module 4
https://circuitpython.org/boards/raspberrypi_cm4
"""
ID_SD: microcontroller.Pin = ...
ID_SC: microcontroller.Pin = ...
GPIO2: microcontroller.Pin = ...
GPIO3: microcontroller.Pin = ...
GPIO4: microcontroller.Pin = ...
GPIO5: microcontroller.Pin = ...
GPIO6: microcontroller.Pin = ...
GPIO7: microcontroller.Pin = ...
GPIO8: microcontroller.Pin = ...
GPIO9: microcontroller.Pin = ...
GPIO10: microcontroller.Pin = ...
GPIO11: microcontroller.Pin = ...
GPIO12: microcontroller.Pin = ...
GPIO13: microcontroller.Pin = ...
GPIO14: microcontroller.Pin = ...
GPIO15: microcontroller.Pin = ...
GPIO16: microcontroller.Pin = ...
GPIO17: microcontroller.Pin = ...
GPIO18: microcontroller.Pin = ...
GPIO19: microcontroller.Pin = ...
GPIO20: microcontroller.Pin = ...
GPIO21: microcontroller.Pin = ...
GPIO22: microcontroller.Pin = ...
GPIO23: microcontroller.Pin = ...
GPIO24: microcontroller.Pin = ...
GPIO25: microcontroller.Pin = ...
GPIO26: microcontroller.Pin = ...
GPIO27: microcontroller.Pin = ...
LED_nACT: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
SDA0: microcontroller.Pin = ...
SCL0: microcontroller.Pin = ...
DISPLAY: displayio.Display = ...
