from __future__ import annotations
import busio
import displayio
import microcontroller
import typing
"""
board Pimoroni Inky Frame 5.7
https://circuitpython.org/boards/pimoroni_inky_frame_5_7
"""
TX: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
HOLD_SYS_EN: microcontroller.Pin = ...
I2C_INT: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
LED_ACT: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
LED_CONN: microcontroller.Pin = ...
SWITCH_CLK: microcontroller.Pin = ...
SWITCH_LATCH: microcontroller.Pin = ...
SWITCH_OUT: microcontroller.Pin = ...
LED_A: microcontroller.Pin = ...
LED_B: microcontroller.Pin = ...
LED_C: microcontroller.Pin = ...
LED_D: microcontroller.Pin = ...
LED_E: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
INKY_CS: microcontroller.Pin = ...
SCLK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
SD_DAT1: microcontroller.Pin = ...
SD_DAT2: microcontroller.Pin = ...
SD_CS: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
INKY_RES: microcontroller.Pin = ...
INKY_DC: microcontroller.Pin = ...
SMPS_MODE: microcontroller.Pin = ...
VBUS_SENSE: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
DISPLAY: displayio.Display = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

