from __future__ import annotations
import busio
import microcontroller
"""
board ElectronicCats Bast WiFi
https://circuitpython.org/boards/electroniccats_bastwifi
"""
IO0: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
IO1: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
IO2: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
IO3: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
IO4: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
IO5: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
IO6: microcontroller.Pin = ...
A6: microcontroller.Pin = ...
IO7: microcontroller.Pin = ...
IO8: microcontroller.Pin = ...
IO9: microcontroller.Pin = ...
IO10: microcontroller.Pin = ...
IO11: microcontroller.Pin = ...
IO12: microcontroller.Pin = ...
IO13: microcontroller.Pin = ...
IO14: microcontroller.Pin = ...
IO15: microcontroller.Pin = ...
IO16: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
IO17: microcontroller.Pin = ...
IO18: microcontroller.Pin = ...
IO19: microcontroller.Pin = ...
IO20: microcontroller.Pin = ...
IO21: microcontroller.Pin = ...
IO26: microcontroller.Pin = ...
IO33: microcontroller.Pin = ...
IO34: microcontroller.Pin = ...
IO35: microcontroller.Pin = ...
IO36: microcontroller.Pin = ...
IO37: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
CS: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
IO38: microcontroller.Pin = ...
IO39: microcontroller.Pin = ...
IO40: microcontroller.Pin = ...
IO41: microcontroller.Pin = ...
IO42: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
IO43: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
IO44: microcontroller.Pin = ...
IO45: microcontroller.Pin = ...
IO46: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

