from __future__ import annotations
import busio
import microcontroller
"""
board Electronic Cats NFC Copy Cat
https://circuitpython.org/boards/nfc_copy_cat
"""
D2: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
D27: microcontroller.Pin = ...
D28: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
D18: microcontroller.Pin = ...
def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


