from __future__ import annotations
import busio
import displayio
import microcontroller
import typing
"""
board HiiBot HiiBot BlueFi
https://circuitpython.org/boards/hiibot_bluefi
"""
P0: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
P1: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
P2: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
P3: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
P4: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
P5: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
BUTTON_A: microcontroller.Pin = ...
P6: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
P7: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
P8: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
P9: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
P10: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
P11: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
BUTTON_B: microcontroller.Pin = ...
P12: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
P13: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
P14: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
P15: microcontroller.Pin = ...
D15: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
P16: microcontroller.Pin = ...
D16: microcontroller.Pin = ...
P17: microcontroller.Pin = ...
D17: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
REDLED: microcontroller.Pin = ...
P18: microcontroller.Pin = ...
D18: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
P19: microcontroller.Pin = ...
D19: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
P20: microcontroller.Pin = ...
D20: microcontroller.Pin = ...
A6: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
P21: microcontroller.Pin = ...
D21: microcontroller.Pin = ...
MICROPHONE_CLOCK: microcontroller.Pin = ...
P22: microcontroller.Pin = ...
D22: microcontroller.Pin = ...
MICROPHONE_DATA: microcontroller.Pin = ...
P23: microcontroller.Pin = ...
D23: microcontroller.Pin = ...
TFT_SCK: microcontroller.Pin = ...
P24: microcontroller.Pin = ...
D24: microcontroller.Pin = ...
TFT_MOSI: microcontroller.Pin = ...
P25: microcontroller.Pin = ...
D25: microcontroller.Pin = ...
TFT_CS: microcontroller.Pin = ...
P26: microcontroller.Pin = ...
D26: microcontroller.Pin = ...
TFT_DC: microcontroller.Pin = ...
P27: microcontroller.Pin = ...
D27: microcontroller.Pin = ...
TFT_BACKLIGHT: microcontroller.Pin = ...
P34: microcontroller.Pin = ...
D34: microcontroller.Pin = ...
WIFI_SCK: microcontroller.Pin = ...
P35: microcontroller.Pin = ...
D35: microcontroller.Pin = ...
WIFI_MISO: microcontroller.Pin = ...
P36: microcontroller.Pin = ...
D36: microcontroller.Pin = ...
WIFI_MOSI: microcontroller.Pin = ...
P37: microcontroller.Pin = ...
D37: microcontroller.Pin = ...
WIFI_BUSY: microcontroller.Pin = ...
P38: microcontroller.Pin = ...
D38: microcontroller.Pin = ...
WIFI_CS: microcontroller.Pin = ...
P39: microcontroller.Pin = ...
D39: microcontroller.Pin = ...
WIFI_RESET: microcontroller.Pin = ...
P40: microcontroller.Pin = ...
D40: microcontroller.Pin = ...
WIFI_PWR: microcontroller.Pin = ...
P41: microcontroller.Pin = ...
D41: microcontroller.Pin = ...
SENSORS_SCL: microcontroller.Pin = ...
P42: microcontroller.Pin = ...
D42: microcontroller.Pin = ...
SENSORS_SDA: microcontroller.Pin = ...
P43: microcontroller.Pin = ...
D43: microcontroller.Pin = ...
IMU_IRQ: microcontroller.Pin = ...
ACCELEROMETER_INTERRUPT: microcontroller.Pin = ...
P44: microcontroller.Pin = ...
D44: microcontroller.Pin = ...
WHITELED: microcontroller.Pin = ...
P45: microcontroller.Pin = ...
D45: microcontroller.Pin = ...
SPEAKER_ENABLE: microcontroller.Pin = ...
P46: microcontroller.Pin = ...
D46: microcontroller.Pin = ...
SPEAKER: microcontroller.Pin = ...
AUDIO: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
DISPLAY: displayio.Display = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

