from __future__ import annotations
import busio
import microcontroller
import typing
"""
board UnexpectedMaker ProS3
https://circuitpython.org/boards/unexpectedmaker_pros3
"""
IO0: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
IO1: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
IO2: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
IO3: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
IO4: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
IO5: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
IO6: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
IO7: microcontroller.Pin = ...
A6: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
IO8: microcontroller.Pin = ...
A7: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
IO9: microcontroller.Pin = ...
A8: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
IO12: microcontroller.Pin = ...
A11: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
IO13: microcontroller.Pin = ...
A12: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
IO14: microcontroller.Pin = ...
A13: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
IO15: microcontroller.Pin = ...
A14: microcontroller.Pin = ...
D15: microcontroller.Pin = ...
IO16: microcontroller.Pin = ...
A15: microcontroller.Pin = ...
D16: microcontroller.Pin = ...
IO21: microcontroller.Pin = ...
D21: microcontroller.Pin = ...
IO34: microcontroller.Pin = ...
D34: microcontroller.Pin = ...
IO35: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MO: microcontroller.Pin = ...
SDO: microcontroller.Pin = ...
D35: microcontroller.Pin = ...
IO37: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
MI: microcontroller.Pin = ...
SDI: microcontroller.Pin = ...
D37: microcontroller.Pin = ...
IO36: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
D36: microcontroller.Pin = ...
IO38: microcontroller.Pin = ...
D38: microcontroller.Pin = ...
IO39: microcontroller.Pin = ...
MTCK: microcontroller.Pin = ...
D39: microcontroller.Pin = ...
IO40: microcontroller.Pin = ...
MTDO: microcontroller.Pin = ...
D40: microcontroller.Pin = ...
IO41: microcontroller.Pin = ...
MTDI: microcontroller.Pin = ...
D41: microcontroller.Pin = ...
IO42: microcontroller.Pin = ...
MTMS: microcontroller.Pin = ...
D42: microcontroller.Pin = ...
IO43: microcontroller.Pin = ...
D43: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
IO44: microcontroller.Pin = ...
D44: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
BATTERY: microcontroller.Pin = ...
VBAT: microcontroller.Pin = ...
VBAT_SENSE: microcontroller.Pin = ...
VOLTAGE_MONITOR: microcontroller.Pin = ...
VBUS: microcontroller.Pin = ...
VBUS_SENSE: microcontroller.Pin = ...
NEOPIXEL_POWER: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
LDO2: microcontroller.Pin = ...
IO17: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

