from __future__ import annotations
import busio
import microcontroller
"""
board Robotics Masters Robo HAT MM1 M4
https://circuitpython.org/boards/robohatmm1_m4
"""
SERVO1: microcontroller.Pin = ...
SERVO2: microcontroller.Pin = ...
SERVO3: microcontroller.Pin = ...
SERVO4: microcontroller.Pin = ...
SERVO5: microcontroller.Pin = ...
SERVO6: microcontroller.Pin = ...
SERVO7: microcontroller.Pin = ...
SERVO8: microcontroller.Pin = ...
RCC1: microcontroller.Pin = ...
RCC2: microcontroller.Pin = ...
RCC3: microcontroller.Pin = ...
RCC4: microcontroller.Pin = ...
VOLTAGE_MONITOR: microcontroller.Pin = ...
BATTERY: microcontroller.Pin = ...
POWER_OFF: microcontroller.Pin = ...
POWER_DISABLE: microcontroller.Pin = ...
POWER_ON: microcontroller.Pin = ...
POWER_ENABLE: microcontroller.Pin = ...
BUTTON: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
GROVE_SCL: microcontroller.Pin = ...
GROVE_SDA: microcontroller.Pin = ...
GROVE_RX: microcontroller.Pin = ...
GROVE_TX: microcontroller.Pin = ...
GROVE_D1: microcontroller.Pin = ...
GROVE_D0: microcontroller.Pin = ...
GROVE_A1: microcontroller.Pin = ...
GROVE_A0: microcontroller.Pin = ...
UART_TX: microcontroller.Pin = ...
UART_RX: microcontroller.Pin = ...
UART_CTS: microcontroller.Pin = ...
UART_RTS: microcontroller.Pin = ...
TX1: microcontroller.Pin = ...
RX1: microcontroller.Pin = ...
PI_TX: microcontroller.Pin = ...
PI_RX: microcontroller.Pin = ...
SDA1: microcontroller.Pin = ...
SCL1: microcontroller.Pin = ...
FLASH_SCK: microcontroller.Pin = ...
FLASH_MISO: microcontroller.Pin = ...
FLASH_MOSI: microcontroller.Pin = ...
FLASH_CS: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
PI_SDA: microcontroller.Pin = ...
PI_SCL: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
SS: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
GPS_TX: microcontroller.Pin = ...
GPS_RX: microcontroller.Pin = ...
PI_GP25: microcontroller.Pin = ...
SWCLK: microcontroller.Pin = ...
PI_GP24: microcontroller.Pin = ...
SWDIO: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


