from __future__ import annotations
import busio
import microcontroller
"""
board STMicroelectronics STM32F412ZG Discovery Board - CPy
https://circuitpython.org/boards/stm32f412zg_discovery
"""
PE02: microcontroller.Pin = ...
PE03: microcontroller.Pin = ...
PE04: microcontroller.Pin = ...
PE05: microcontroller.Pin = ...
PE06: microcontroller.Pin = ...
PC13: microcontroller.Pin = ...
PF02: microcontroller.Pin = ...
PF03: microcontroller.Pin = ...
PF10: microcontroller.Pin = ...
PC00: microcontroller.Pin = ...
PC01: microcontroller.Pin = ...
PC02: microcontroller.Pin = ...
PC03: microcontroller.Pin = ...
PA01: microcontroller.Pin = ...
PA02: microcontroller.Pin = ...
PA03: microcontroller.Pin = ...
PA04: microcontroller.Pin = ...
PA05: microcontroller.Pin = ...
PA06: microcontroller.Pin = ...
PA07: microcontroller.Pin = ...
PC04: microcontroller.Pin = ...
PC05: microcontroller.Pin = ...
PB00: microcontroller.Pin = ...
PB01: microcontroller.Pin = ...
PF11: microcontroller.Pin = ...
PF13: microcontroller.Pin = ...
PB10: microcontroller.Pin = ...
PB11: microcontroller.Pin = ...
PB12: microcontroller.Pin = ...
PB13: microcontroller.Pin = ...
PB14: microcontroller.Pin = ...
PB15: microcontroller.Pin = ...
PD12: microcontroller.Pin = ...
PD13: microcontroller.Pin = ...
PG02: microcontroller.Pin = ...
PC06: microcontroller.Pin = ...
PC07: microcontroller.Pin = ...
PC09: microcontroller.Pin = ...
PA08: microcontroller.Pin = ...
PA10: microcontroller.Pin = ...
PA13: microcontroller.Pin = ...
PA14: microcontroller.Pin = ...
PA15: microcontroller.Pin = ...
PD06: microcontroller.Pin = ...
PG09: microcontroller.Pin = ...
PG10: microcontroller.Pin = ...
PG11: microcontroller.Pin = ...
PG12: microcontroller.Pin = ...
PG13: microcontroller.Pin = ...
PG14: microcontroller.Pin = ...
PB03: microcontroller.Pin = ...
PB04: microcontroller.Pin = ...
PB05: microcontroller.Pin = ...
PB06: microcontroller.Pin = ...
PB07: microcontroller.Pin = ...
PB08: microcontroller.Pin = ...
PB09: microcontroller.Pin = ...
PE00: microcontroller.Pin = ...
PE01: microcontroller.Pin = ...
D15: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
LED1: microcontroller.Pin = ...
LED2: microcontroller.Pin = ...
LED3: microcontroller.Pin = ...
LED4: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


