from __future__ import annotations
import busio
import microcontroller
"""
board keithp.com snekboard
https://circuitpython.org/boards/snekboard
"""
A1: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
A6: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
A7: microcontroller.Pin = ...
A8: microcontroller.Pin = ...
POWER1: microcontroller.Pin = ...
DIR1: microcontroller.Pin = ...
POWER2: microcontroller.Pin = ...
DIR2: microcontroller.Pin = ...
POWER3: microcontroller.Pin = ...
DIR3: microcontroller.Pin = ...
POWER4: microcontroller.Pin = ...
DIR4: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

