from __future__ import annotations
import busio
import microcontroller
import typing
"""
board Adafruit QT2040 Trinkey
https://circuitpython.org/boards/adafruit_qt2040_trinkey
"""
SDA: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
BUTTON: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

