from __future__ import annotations
import busio
import microcontroller
"""
board Makerdiary M60 Keyboard
https://circuitpython.org/boards/makerdiary_m60_keyboard
"""
R1: microcontroller.Pin = ...
R2: microcontroller.Pin = ...
R3: microcontroller.Pin = ...
R4: microcontroller.Pin = ...
R5: microcontroller.Pin = ...
R6: microcontroller.Pin = ...
R7: microcontroller.Pin = ...
R8: microcontroller.Pin = ...
C1: microcontroller.Pin = ...
C2: microcontroller.Pin = ...
C3: microcontroller.Pin = ...
C4: microcontroller.Pin = ...
C5: microcontroller.Pin = ...
C6: microcontroller.Pin = ...
C7: microcontroller.Pin = ...
C8: microcontroller.Pin = ...
TXD: microcontroller.Pin = ...
RXD: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
LED_R: microcontroller.Pin = ...
LED_G: microcontroller.Pin = ...
LED_B: microcontroller.Pin = ...
BTN: microcontroller.Pin = ...
CHARGING: microcontroller.Pin = ...
VOLTAGE_MONITOR: microcontroller.Pin = ...
BATTERY: microcontroller.Pin = ...
BATTERY_ENABLE: microcontroller.Pin = ...
RGB_POWER: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


