from __future__ import annotations
import busio
import displayio
import microcontroller
"""
board Radomir Dopieralski uGame22
https://circuitpython.org/boards/ugame22
"""
TFT_RST: microcontroller.Pin = ...
TFT_SCK: microcontroller.Pin = ...
TFT_MOSI: microcontroller.Pin = ...
TFT_DC: microcontroller.Pin = ...
TFT_CS: microcontroller.Pin = ...
BUTTON_Z: microcontroller.Pin = ...
BUTTON_X: microcontroller.Pin = ...
BUTTON_DOWN: microcontroller.Pin = ...
BUTTON_O: microcontroller.Pin = ...
BUTTON_RIGHT: microcontroller.Pin = ...
BUTTON_UP: microcontroller.Pin = ...
BUTTON_LEFT: microcontroller.Pin = ...
GAIN: microcontroller.Pin = ...
I2S_DIN: microcontroller.Pin = ...
I2S_BCLK: microcontroller.Pin = ...
I2S_LRCLK: microcontroller.Pin = ...
DISPLAY: displayio.Display = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


