from __future__ import annotations
import busio
import microcontroller
import typing
"""
board espressif_esp32_eye
https://circuitpython.org/boards/espressif_esp32_eye
"""
I2S_SCK: microcontroller.Pin = ...
I2S_WS: microcontroller.Pin = ...
I2S_SDO: microcontroller.Pin = ...
BOOT: microcontroller.Pin = ...
BUTTON: microcontroller.Pin = ...
LED_RED: microcontroller.Pin = ...
LED_WHITE: microcontroller.Pin = ...
CAMERA_DATA: typing.Any = ...
CAMERA_VSYNC: microcontroller.Pin = ...
CAMERA_HREF: microcontroller.Pin = ...
CAMERA_PCLK: microcontroller.Pin = ...
CAMERA_XCLK: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


