from __future__ import annotations
import microcontroller
"""
board Espruino Espruino Wifi
https://circuitpython.org/boards/espruino_wifi
"""
A0: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
A6: microcontroller.Pin = ...
A7: microcontroller.Pin = ...
B1: microcontroller.Pin = ...
B10: microcontroller.Pin = ...
B13: microcontroller.Pin = ...
B14: microcontroller.Pin = ...
B15: microcontroller.Pin = ...
B0: microcontroller.Pin = ...
B9: microcontroller.Pin = ...
B8: microcontroller.Pin = ...
B7: microcontroller.Pin = ...
B6: microcontroller.Pin = ...
B5: microcontroller.Pin = ...
B4: microcontroller.Pin = ...
B3: microcontroller.Pin = ...
A10: microcontroller.Pin = ...
A8: microcontroller.Pin = ...
LED1: microcontroller.Pin = ...
LED2: microcontroller.Pin = ...
BTN: microcontroller.Pin = ...
ESP_RX: microcontroller.Pin = ...
ESP_TX: microcontroller.Pin = ...
ESP_GPIO0: microcontroller.Pin = ...
ESP_CHPD: microcontroller.Pin = ...
ESP_GPIO13: microcontroller.Pin = ...
