from __future__ import annotations
import microcontroller
"""
board Teknikio Bluebird
https://circuitpython.org/boards/teknikio_bluebird
"""
P0_12: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
P0_11: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
P1_09: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
P1_08: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
P0_08: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
P0_07: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
P0_06: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
P0_05: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
P0_04: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
A6: microcontroller.Pin = ...
P0_29: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
P0_31: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
P0_02: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
P0_03: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
LIGHT: microcontroller.Pin = ...
LIGHT_ENABLE: microcontroller.Pin = ...
SPEAKER: microcontroller.Pin = ...
ACCELEROMETER_INTERRUPT: microcontroller.Pin = ...
ACCELEROMETER_SDA: microcontroller.Pin = ...
ACCELEROMETER_SCL: microcontroller.Pin = ...
