from __future__ import annotations
import busio
import microcontroller
"""
board 0xCB Helios
https://circuitpython.org/boards/0xcb_helios
"""
GP10: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
GP1: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
GP0: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
GP2: microcontroller.Pin = ...
GP3: microcontroller.Pin = ...
GP4: microcontroller.Pin = ...
GP5: microcontroller.Pin = ...
GP6: microcontroller.Pin = ...
GP7: microcontroller.Pin = ...
GP8: microcontroller.Pin = ...
GP9: microcontroller.Pin = ...
GP11: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
GP29: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
GP28: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
GP27: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
GP26: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
GP22: microcontroller.Pin = ...
SDI: microcontroller.Pin = ...
GP20: microcontroller.Pin = ...
SDO: microcontroller.Pin = ...
GP23: microcontroller.Pin = ...
CS: microcontroller.Pin = ...
GP21: microcontroller.Pin = ...
GP12: microcontroller.Pin = ...
GP13: microcontroller.Pin = ...
GP14: microcontroller.Pin = ...
GP15: microcontroller.Pin = ...
GP16: microcontroller.Pin = ...
RGB: microcontroller.Pin = ...
GP25: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
GP17: microcontroller.Pin = ...
VBUS_SENSE: microcontroller.Pin = ...
GP19: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

