from __future__ import annotations
import displayio
import microcontroller
"""
board lilygo_ttgo_tdisplay_esp32_16m
https://circuitpython.org/boards/lilygo_ttgo_tdisplay_esp32_16m
"""
BUTTON0: microcontroller.Pin = ...
IO0: microcontroller.Pin = ...
BUTTON1: microcontroller.Pin = ...
IO35: microcontroller.Pin = ...
IO2: microcontroller.Pin = ...
IO12: microcontroller.Pin = ...
IO13: microcontroller.Pin = ...
IO15: microcontroller.Pin = ...
IO17: microcontroller.Pin = ...
IO21: microcontroller.Pin = ...
IO22: microcontroller.Pin = ...
IO25: microcontroller.Pin = ...
IO26: microcontroller.Pin = ...
IO27: microcontroller.Pin = ...
IO32: microcontroller.Pin = ...
IO33: microcontroller.Pin = ...
IO37: microcontroller.Pin = ...
IO38: microcontroller.Pin = ...
LCD_MOSI: microcontroller.Pin = ...
LCD_CLK: microcontroller.Pin = ...
LCD_CS: microcontroller.Pin = ...
LCD_RST: microcontroller.Pin = ...
LCD_BCKL: microcontroller.Pin = ...
LCD_D_C: microcontroller.Pin = ...
DISPLAY: displayio.Display = ...
BATTERY: microcontroller.Pin = ...
