from __future__ import annotations
import busio
import microcontroller
"""
board lilygo_ttgo_t-oi-plus
https://circuitpython.org/boards/lilygo_ttgo_t-oi-plus
"""
IO2: microcontroller.Pin = ...
BATTERY: microcontroller.Pin = ...
VOLTAGE_MONITOR: microcontroller.Pin = ...
IO8: microcontroller.Pin = ...
IO9: microcontroller.Pin = ...
IO4: microcontroller.Pin = ...
IO5: microcontroller.Pin = ...
IO6: microcontroller.Pin = ...
IO7: microcontroller.Pin = ...
IO10: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
IO20: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
IO21: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
IO19: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
IO18: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
IO3: microcontroller.Pin = ...
def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

