from __future__ import annotations
import busio
import microcontroller
"""
board VCC-GND YD-ESP32-S3
https://circuitpython.org/boards/yd_esp32_s3_n16r8
"""
GPIO4: microcontroller.Pin = ...
GPIO5: microcontroller.Pin = ...
GPIO6: microcontroller.Pin = ...
GPIO7: microcontroller.Pin = ...
GPIO15: microcontroller.Pin = ...
GPIO16: microcontroller.Pin = ...
GPIO17: microcontroller.Pin = ...
GPIO18: microcontroller.Pin = ...
GPIO8: microcontroller.Pin = ...
GPIO3: microcontroller.Pin = ...
GPIO46: microcontroller.Pin = ...
GPIO9: microcontroller.Pin = ...
GPIO10: microcontroller.Pin = ...
GPIO11: microcontroller.Pin = ...
GPIO12: microcontroller.Pin = ...
GPIO13: microcontroller.Pin = ...
GPIO14: microcontroller.Pin = ...
GPIO43: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
GPIO44: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
GPIO1: microcontroller.Pin = ...
GPIO2: microcontroller.Pin = ...
GPIO14: microcontroller.Pin = ...
GPIO42: microcontroller.Pin = ...
GPIO41: microcontroller.Pin = ...
GPIO40: microcontroller.Pin = ...
GPIO39: microcontroller.Pin = ...
GPIO38: microcontroller.Pin = ...
GPIO37: microcontroller.Pin = ...
GPIO36: microcontroller.Pin = ...
GPIO35: microcontroller.Pin = ...
GPIO0: microcontroller.Pin = ...
BOOT: microcontroller.Pin = ...
GPIO45: microcontroller.Pin = ...
GPIO48: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
GPIO47: microcontroller.Pin = ...
GPIO21: microcontroller.Pin = ...
def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

