from __future__ import annotations
import busio
import displayio
import microcontroller
"""
board Diodes Delight Piunora
https://circuitpython.org/boards/diodes_delight_piunora
"""
GPIO5: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
GPIO4: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
GPIO18: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
GPIO19: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
GPIO20: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
GPIO21: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
GPIO22: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
SDA6: microcontroller.Pin = ...
GPIO23: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
SCL6: microcontroller.Pin = ...
GPIO6: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
SDA4: microcontroller.Pin = ...
GPIO7: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
SCL4: microcontroller.Pin = ...
SPI0_CE1: microcontroller.Pin = ...
GPIO8: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
SPI0_CE0: microcontroller.Pin = ...
GPIO10: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
SPI0_MOSI: microcontroller.Pin = ...
GPIO9: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
SPI0_MISO: microcontroller.Pin = ...
GPIO11: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
SPI0_SCLK: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SDA1: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
GPIO12: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
DISPLAY: displayio.Display = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


