from __future__ import annotations
import busio
import microcontroller
import typing
"""
board Adafruit MatrixPortal S3
https://circuitpython.org/boards/adafruit_matrixportal_s3
"""
BUTTON: microcontroller.Pin = ...
BOOT0: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
D16: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D17: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
L: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
D18: microcontroller.Pin = ...
ACCELEROMETER_INTERRUPT: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

