from __future__ import annotations
import busio
import microcontroller
import typing
"""
board m5stack_atom_matrix
https://circuitpython.org/boards/m5stack_atom_matrix
"""
D22: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
D19: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
D23: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
D33: microcontroller.Pin = ...
A33: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D21: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
A25: microcontroller.Pin = ...
D25: microcontroller.Pin = ...
DAC1: microcontroller.Pin = ...
PORTA_SDA: microcontroller.Pin = ...
A26: microcontroller.Pin = ...
D26: microcontroller.Pin = ...
DAC2: microcontroller.Pin = ...
PORTA_SCL: microcontroller.Pin = ...
A32: microcontroller.Pin = ...
D32: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
BTN: microcontroller.Pin = ...
IR_LED: microcontroller.Pin = ...
PORTA_I2C: typing.Any = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


