from __future__ import annotations
import busio
import microcontroller
"""
board NXP IMXRT1010-EVK
https://circuitpython.org/boards/imxrt1010_evk
"""
AUDIO_INT: microcontroller.Pin = ...
AUDIO_SYNC: microcontroller.Pin = ...
AUDIO_BCLK: microcontroller.Pin = ...
AUDIO_RXD: microcontroller.Pin = ...
AUDIO_TXD: microcontroller.Pin = ...
AUDIO_MCLK: microcontroller.Pin = ...
SPDIF_IN: microcontroller.Pin = ...
SPDIF_OUT: microcontroller.Pin = ...
FREELINK_TX: microcontroller.Pin = ...
FREELINK_RX: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

