from __future__ import annotations
import busio
import microcontroller
"""
board Cedar Grove Studios StringCar M0 Express
https://circuitpython.org/boards/stringcar_m0_express
"""
PIEZO: microcontroller.Pin = ...
VOLTAGE_MONITOR: microcontroller.Pin = ...
SENSOR_IN: microcontroller.Pin = ...
MOTOR_OUT_1: microcontroller.Pin = ...
MOTOR_OUT_2: microcontroller.Pin = ...
LED_STATUS: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
DOTSTAR_DI: microcontroller.Pin = ...
DOTSTAR_CI: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


