from __future__ import annotations
import busio
import microcontroller
"""
board espressif_esp32_lyrat
https://circuitpython.org/boards/espressif_esp32_lyrat
"""
CS0: microcontroller.Pin = ...
D15: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D23: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
D18: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
D25: microcontroller.Pin = ...
D26: microcontroller.Pin = ...
D35: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
L: microcontroller.Pin = ...
D22: microcontroller.Pin = ...
BUTTON: microcontroller.Pin = ...
REC: microcontroller.Pin = ...
SW36: microcontroller.Pin = ...
BUTTON: microcontroller.Pin = ...
MODE: microcontroller.Pin = ...
SW39: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


