from __future__ import annotations
import microcontroller
"""
board Adafruit Industries LLC Slide Trinkey M0
https://circuitpython.org/boards/adafruit_slide_trinkey_m0
"""
NEOPIXEL: microcontroller.Pin = ...
POTENTIOMETER: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
TOUCH: microcontroller.Pin = ...
