from __future__ import annotations
import microcontroller
"""
board Foosn Fomu
https://circuitpython.org/boards/fomu
"""
TOUCH1: microcontroller.Pin = ...
TOUCH2: microcontroller.Pin = ...
TOUCH3: microcontroller.Pin = ...
TOUCH4: microcontroller.Pin = ...
