from __future__ import annotations
import microcontroller
"""
board makerdiary nRF52840-MDK
https://circuitpython.org/boards/makerdiary_nrf52840_mdk
"""
AIN0: microcontroller.Pin = ...
AIN1: microcontroller.Pin = ...
AIN2: microcontroller.Pin = ...
AIN3: microcontroller.Pin = ...
AIN4: microcontroller.Pin = ...
AIN5: microcontroller.Pin = ...
AIN6: microcontroller.Pin = ...
AIN7: microcontroller.Pin = ...
AREF: microcontroller.Pin = ...
VDIV: microcontroller.Pin = ...
NFC1: microcontroller.Pin = ...
NFC2: microcontroller.Pin = ...
P2: microcontroller.Pin = ...
P3: microcontroller.Pin = ...
P4: microcontroller.Pin = ...
P5: microcontroller.Pin = ...
P6: microcontroller.Pin = ...
P7: microcontroller.Pin = ...
P8: microcontroller.Pin = ...
P9: microcontroller.Pin = ...
P10: microcontroller.Pin = ...
P11: microcontroller.Pin = ...
P12: microcontroller.Pin = ...
P13: microcontroller.Pin = ...
P14: microcontroller.Pin = ...
P15: microcontroller.Pin = ...
P16: microcontroller.Pin = ...
P17: microcontroller.Pin = ...
P21: microcontroller.Pin = ...
P25: microcontroller.Pin = ...
P26: microcontroller.Pin = ...
P27: microcontroller.Pin = ...
P28: microcontroller.Pin = ...
P29: microcontroller.Pin = ...
P30: microcontroller.Pin = ...
P31: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
CSN: microcontroller.Pin = ...
IO0: microcontroller.Pin = ...
IO1: microcontroller.Pin = ...
IO2: microcontroller.Pin = ...
IO3: microcontroller.Pin = ...
TXD: microcontroller.Pin = ...
RXD: microcontroller.Pin = ...
LED_RED: microcontroller.Pin = ...
LED_GREEN: microcontroller.Pin = ...
LED_BLUE: microcontroller.Pin = ...
BUTTON_USR: microcontroller.Pin = ...
