from __future__ import annotations
import busio
import displayio
import microcontroller
import typing
"""
board 01space_lcd042_esp32c3
https://circuitpython.org/boards/01space_lcd042_esp32c3
"""
IO0: microcontroller.Pin = ...
IO1: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
IO2: microcontroller.Pin = ...
IO3: microcontroller.Pin = ...
IO4: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
IO5: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
IO6: microcontroller.Pin = ...
IO7: microcontroller.Pin = ...
IO8: microcontroller.Pin = ...
BUTTON: microcontroller.Pin = ...
IO9: microcontroller.Pin = ...
IO10: microcontroller.Pin = ...
IO20: microcontroller.Pin = ...
IO21: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
DISPLAY: displayio.Display = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


