from __future__ import annotations
import busio
import microcontroller
"""
board Pimoroni Keybow 2040
https://circuitpython.org/boards/pimoroni_keybow2040
"""
TX: microcontroller.Pin = ...
GP0: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
GP1: microcontroller.Pin = ...
INT: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SW0: microcontroller.Pin = ...
SW1: microcontroller.Pin = ...
SW2: microcontroller.Pin = ...
SW3: microcontroller.Pin = ...
SW4: microcontroller.Pin = ...
SW5: microcontroller.Pin = ...
SW6: microcontroller.Pin = ...
SW7: microcontroller.Pin = ...
SW8: microcontroller.Pin = ...
SW9: microcontroller.Pin = ...
SW10: microcontroller.Pin = ...
SW11: microcontroller.Pin = ...
SW12: microcontroller.Pin = ...
SW13: microcontroller.Pin = ...
SW14: microcontroller.Pin = ...
SW15: microcontroller.Pin = ...
USER_SW: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

