from __future__ import annotations
import busio
import microcontroller
"""
board Winterbloom Sol
https://circuitpython.org/boards/winterbloom_sol
"""
SCK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
DAC_CS: microcontroller.Pin = ...
G1: microcontroller.Pin = ...
G2: microcontroller.Pin = ...
G3: microcontroller.Pin = ...
G4: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


