from __future__ import annotations
import busio
import microcontroller
"""
board adafruit_feather_huzzah32
https://circuitpython.org/boards/adafruit_feather_huzzah32
"""
A0: microcontroller.Pin = ...
D26: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
D25: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
D34: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
D39: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
D36: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
D18: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
D19: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
D16: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
D17: microcontroller.Pin = ...
D21: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
A12: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
A11: microcontroller.Pin = ...
D27: microcontroller.Pin = ...
A10: microcontroller.Pin = ...
D33: microcontroller.Pin = ...
A9: microcontroller.Pin = ...
D15: microcontroller.Pin = ...
A8: microcontroller.Pin = ...
D32: microcontroller.Pin = ...
A7: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
A6: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D22: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
D23: microcontroller.Pin = ...
D35: microcontroller.Pin = ...
VOLTAGE_MONITOR: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

