from __future__ import annotations
import microcontroller
"""
board Raytac Corporation MDBT50Q-RX Dongle
https://circuitpython.org/boards/raytac_mdbt50q-rx
"""
P0_15: microcontroller.Pin = ...
BUTTON: microcontroller.Pin = ...
P1_13: microcontroller.Pin = ...
INVERTED_LED: microcontroller.Pin = ...
