from __future__ import annotations
import busio
import microcontroller
"""
board Jeremy Gillick Thunderpack STM32F411
https://circuitpython.org/boards/thunderpack_v11
"""
PA0: microcontroller.Pin = ...
PA1: microcontroller.Pin = ...
PA2: microcontroller.Pin = ...
PA3: microcontroller.Pin = ...
PA4: microcontroller.Pin = ...
PA5: microcontroller.Pin = ...
PA6: microcontroller.Pin = ...
PA7: microcontroller.Pin = ...
PA8: microcontroller.Pin = ...
PA9: microcontroller.Pin = ...
PA10: microcontroller.Pin = ...
PA13: microcontroller.Pin = ...
PA14: microcontroller.Pin = ...
PB5: microcontroller.Pin = ...
PB6: microcontroller.Pin = ...
PB7: microcontroller.Pin = ...
LED1: microcontroller.Pin = ...
LED2: microcontroller.Pin = ...
LED3: microcontroller.Pin = ...
LED4: microcontroller.Pin = ...
BUTTON: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


