from __future__ import annotations
import busio
import microcontroller
"""
board Arduino Arduino_Nano_33_BLE
https://circuitpython.org/boards/arduino_nano_33_ble
"""
D2: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
A6: microcontroller.Pin = ...
A7: microcontroller.Pin = ...
SDA1: microcontroller.Pin = ...
SCL1: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
LED_Y: microcontroller.Pin = ...
LED_G: microcontroller.Pin = ...
RGB_LED_R: microcontroller.Pin = ...
RGB_LED_G: microcontroller.Pin = ...
RGB_LED_B: microcontroller.Pin = ...
VDD_ENV: microcontroller.Pin = ...
R_PULLUP: microcontroller.Pin = ...
MIC_PWR: microcontroller.Pin = ...
PDMCLK: microcontroller.Pin = ...
PDMDIN: microcontroller.Pin = ...
INT_APDS: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


