from __future__ import annotations
import busio
import microcontroller
"""
board Makerdiary Makerdiary nRF52840 Connect Kit
https://circuitpython.org/boards/makerdiary_nrf52840_connectkit
"""
P3: microcontroller.Pin = ...
P4: microcontroller.Pin = ...
P5: microcontroller.Pin = ...
P6: microcontroller.Pin = ...
P7: microcontroller.Pin = ...
P8: microcontroller.Pin = ...
P9: microcontroller.Pin = ...
P10: microcontroller.Pin = ...
P11: microcontroller.Pin = ...
P12: microcontroller.Pin = ...
P13: microcontroller.Pin = ...
P14: microcontroller.Pin = ...
P15: microcontroller.Pin = ...
P16: microcontroller.Pin = ...
P18: microcontroller.Pin = ...
P24: microcontroller.Pin = ...
P25: microcontroller.Pin = ...
P26: microcontroller.Pin = ...
P27: microcontroller.Pin = ...
P28: microcontroller.Pin = ...
P29: microcontroller.Pin = ...
P30: microcontroller.Pin = ...
P31: microcontroller.Pin = ...
P32: microcontroller.Pin = ...
P33: microcontroller.Pin = ...
P34: microcontroller.Pin = ...
P35: microcontroller.Pin = ...
P36: microcontroller.Pin = ...
P37: microcontroller.Pin = ...
P38: microcontroller.Pin = ...
P39: microcontroller.Pin = ...
P40: microcontroller.Pin = ...
P41: microcontroller.Pin = ...
P42: microcontroller.Pin = ...
P43: microcontroller.Pin = ...
P44: microcontroller.Pin = ...
P45: microcontroller.Pin = ...
P46: microcontroller.Pin = ...
P47: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
A6: microcontroller.Pin = ...
A7: microcontroller.Pin = ...
MEAS_EN: microcontroller.Pin = ...
MODE: microcontroller.Pin = ...
USER: microcontroller.Pin = ...
RESET: microcontroller.Pin = ...
LED0: microcontroller.Pin = ...
LED1: microcontroller.Pin = ...
LED2: microcontroller.Pin = ...
LED3: microcontroller.Pin = ...
RED_LED: microcontroller.Pin = ...
GREEN_LED: microcontroller.Pin = ...
BLUE_LED: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


