from __future__ import annotations
import microcontroller
import typing
"""
board m5stack_atom_echo
https://circuitpython.org/boards/m5stack_atom_echo
"""
SPK_I2S_SDO: microcontroller.Pin = ...
SPK_I2S_SCK: microcontroller.Pin = ...
SPK_I2S_LRC: microcontroller.Pin = ...
PDM_MIC_CLK: microcontroller.Pin = ...
PDM_MIC_DATA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D21: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
A25: microcontroller.Pin = ...
D25: microcontroller.Pin = ...
DAC1: microcontroller.Pin = ...
PORTA_SDA: microcontroller.Pin = ...
A26: microcontroller.Pin = ...
D26: microcontroller.Pin = ...
DAC2: microcontroller.Pin = ...
PORTA_SCL: microcontroller.Pin = ...
A32: microcontroller.Pin = ...
D32: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
BTN: microcontroller.Pin = ...
IR_LED: microcontroller.Pin = ...
PORTA_I2C: typing.Any = ...
