from __future__ import annotations
import busio
import displayio
import microcontroller
import typing
"""
board Adafruit MagTag
https://circuitpython.org/boards/adafruit_magtag_2
"""
D10: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
AD1: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
SPEAKER: microcontroller.Pin = ...
SPEAKER_ENABLE: microcontroller.Pin = ...
EPD_BUSY: microcontroller.Pin = ...
EPD_RESET: microcontroller.Pin = ...
EPD_DC: microcontroller.Pin = ...
EPD_CS: microcontroller.Pin = ...
EPD_MOSI: microcontroller.Pin = ...
EPD_SCK: microcontroller.Pin = ...
EPD_MISO: microcontroller.Pin = ...
BUTTON_A: microcontroller.Pin = ...
D15: microcontroller.Pin = ...
BUTTON_B: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
BUTTON_C: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
BUTTON_D: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
BOOT0: microcontroller.Pin = ...
LIGHT: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
VOLTAGE_MONITOR: microcontroller.Pin = ...
BATTERY: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
NEOPIXEL_POWER_INVERTED: microcontroller.Pin = ...
NEOPIXEL_POWER: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
DISPLAY: displayio.Display = ...
ACCELEROMETER_INTERRUPT: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


