from __future__ import annotations
import busio
import microcontroller
"""
board espressif_esp32c3_devkitm_1_n4
https://circuitpython.org/boards/espressif_esp32c3_devkitm_1_n4
"""
IO0: microcontroller.Pin = ...
IO1: microcontroller.Pin = ...
IO2: microcontroller.Pin = ...
IO3: microcontroller.Pin = ...
IO4: microcontroller.Pin = ...
IO5: microcontroller.Pin = ...
IO6: microcontroller.Pin = ...
IO7: microcontroller.Pin = ...
IO8: microcontroller.Pin = ...
IO9: microcontroller.Pin = ...
IO10: microcontroller.Pin = ...
IO18: microcontroller.Pin = ...
IO19: microcontroller.Pin = ...
IO20: microcontroller.Pin = ...
IO21: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
MTMS: microcontroller.Pin = ...
MTDI: microcontroller.Pin = ...
MTCK: microcontroller.Pin = ...
MTDO: microcontroller.Pin = ...
BUTTON: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

