from __future__ import annotations
import busio
import microcontroller
"""
board m5stack_stamp_c3
https://circuitpython.org/boards/m5stack_stamp_c3
"""
G0: microcontroller.Pin = ...
IO0: microcontroller.Pin = ...
G1: microcontroller.Pin = ...
IO1: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
G2: microcontroller.Pin = ...
IO2: microcontroller.Pin = ...
BUTTON: microcontroller.Pin = ...
G3: microcontroller.Pin = ...
IO3: microcontroller.Pin = ...
G4: microcontroller.Pin = ...
IO4: microcontroller.Pin = ...
G5: microcontroller.Pin = ...
IO5: microcontroller.Pin = ...
G6: microcontroller.Pin = ...
IO6: microcontroller.Pin = ...
G7: microcontroller.Pin = ...
IO7: microcontroller.Pin = ...
G8: microcontroller.Pin = ...
IO8: microcontroller.Pin = ...
G9: microcontroller.Pin = ...
IO9: microcontroller.Pin = ...
G10: microcontroller.Pin = ...
IO10: microcontroller.Pin = ...
G18: microcontroller.Pin = ...
IO18: microcontroller.Pin = ...
G19: microcontroller.Pin = ...
IO19: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
G20: microcontroller.Pin = ...
IO20: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
G21: microcontroller.Pin = ...
IO21: microcontroller.Pin = ...
def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

