from __future__ import annotations
import microcontroller
"""
board Pimoroni Tiny 2040 (2MB)
https://circuitpython.org/boards/pimoroni_tiny2040_2mb
"""
GP0: microcontroller.Pin = ...
GP1: microcontroller.Pin = ...
GP2: microcontroller.Pin = ...
GP3: microcontroller.Pin = ...
GP4: microcontroller.Pin = ...
GP5: microcontroller.Pin = ...
GP6: microcontroller.Pin = ...
GP7: microcontroller.Pin = ...
LED_R: microcontroller.Pin = ...
LED_G: microcontroller.Pin = ...
LED_B: microcontroller.Pin = ...
USER_SW: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
GP26_A0: microcontroller.Pin = ...
GP26: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
GP27_A1: microcontroller.Pin = ...
GP27: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
GP28_A2: microcontroller.Pin = ...
GP28: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
GP29_A3: microcontroller.Pin = ...
GP29: microcontroller.Pin = ...
