from __future__ import annotations
import busio
import microcontroller
import typing
"""
board SparkFun Thing Plus RP2040
https://circuitpython.org/boards/sparkfun_thing_plus_rp2040
"""
D6: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
D23: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D22: microcontroller.Pin = ...
D21: microcontroller.Pin = ...
D20: microcontroller.Pin = ...
D19: microcontroller.Pin = ...
D18: microcontroller.Pin = ...
D17: microcontroller.Pin = ...
D16: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
D29: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
D28: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
D27: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
D26: microcontroller.Pin = ...
SD_SCK: microcontroller.Pin = ...
SD_MOSI: microcontroller.Pin = ...
SD_MISO: microcontroller.Pin = ...
SD_CS: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

