from __future__ import annotations
import busio
import microcontroller
import typing
"""
board Pimoroni Motor 2040
https://circuitpython.org/boards/pimoroni_motor2040
"""
MOTOR_A_P: microcontroller.Pin = ...
MOTOR_A_N: microcontroller.Pin = ...
MOTOR_B_P: microcontroller.Pin = ...
MOTOR_B_N: microcontroller.Pin = ...
MOTOR_C_P: microcontroller.Pin = ...
MOTOR_C_N: microcontroller.Pin = ...
MOTOR_D_P: microcontroller.Pin = ...
MOTOR_D_N: microcontroller.Pin = ...
ENCODER_A_A: microcontroller.Pin = ...
ENCODER_A_B: microcontroller.Pin = ...
ENCODER_B_A: microcontroller.Pin = ...
ENCODER_B_B: microcontroller.Pin = ...
ENCODER_C_A: microcontroller.Pin = ...
ENCODER_C_B: microcontroller.Pin = ...
ENCODER_D_A: microcontroller.Pin = ...
ENCODER_D_B: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
TRIG: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
ECHO: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
LED_DATA: microcontroller.Pin = ...
INT: microcontroller.Pin = ...
GP19: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
GP20: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
GP21: microcontroller.Pin = ...
USER_SW: microcontroller.Pin = ...
ADC_ADDR_0: microcontroller.Pin = ...
ADC_ADDR_1: microcontroller.Pin = ...
ADC_ADDR_2: microcontroller.Pin = ...
GP26_A0: microcontroller.Pin = ...
GP26: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
GP27_A1: microcontroller.Pin = ...
GP27: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
GP28_A2: microcontroller.Pin = ...
GP28: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
SHARED_ADC: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

