from __future__ import annotations
import busio
import displayio
import microcontroller
"""
board Radomir Dopieralski uGame10
https://circuitpython.org/boards/ugame10
"""
X: microcontroller.Pin = ...
O: microcontroller.Pin = ...
SPEAKER: microcontroller.Pin = ...
MUTE: microcontroller.Pin = ...
BATTERY: microcontroller.Pin = ...
UP: microcontroller.Pin = ...
LEFT: microcontroller.Pin = ...
DOWN: microcontroller.Pin = ...
RIGHT: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
DC: microcontroller.Pin = ...
CS: microcontroller.Pin = ...
A: microcontroller.Pin = ...
B: microcontroller.Pin = ...
C: microcontroller.Pin = ...
D: microcontroller.Pin = ...
DISPLAY: displayio.Display = ...
def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


