from __future__ import annotations
import busio
import microcontroller
"""
board Electronic Cats CatWAN USBStick
https://circuitpython.org/boards/catwan_usbstick
"""
D0: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
RFM9X_D0: microcontroller.Pin = ...
RFM9X_D1: microcontroller.Pin = ...
RFM9X_D2: microcontroller.Pin = ...
RFM9X_D5: microcontroller.Pin = ...
RFM9X_RST: microcontroller.Pin = ...
RFM9X_CS: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


