from __future__ import annotations
import displayio
import microcontroller
"""
board Radomir Dopieralski PewPew LCD
https://circuitpython.org/boards/pewpew_lcd
"""
_SCK: microcontroller.Pin = ...
_MOSI: microcontroller.Pin = ...
_CS: microcontroller.Pin = ...
_RST: microcontroller.Pin = ...
_BL: microcontroller.Pin = ...
_UP: microcontroller.Pin = ...
_DOWN: microcontroller.Pin = ...
_LEFT: microcontroller.Pin = ...
_RIGHT: microcontroller.Pin = ...
_O: microcontroller.Pin = ...
_X: microcontroller.Pin = ...
P1: microcontroller.Pin = ...
P2: microcontroller.Pin = ...
P3: microcontroller.Pin = ...
P4: microcontroller.Pin = ...
P5: microcontroller.Pin = ...
P6: microcontroller.Pin = ...
P7: microcontroller.Pin = ...
DISPLAY: displayio.Display = ...
