from __future__ import annotations
import busio
import microcontroller
import typing
"""
board Pimoroni Interstate 75
https://circuitpython.org/boards/pimoroni_interstate75
"""
R0: microcontroller.Pin = ...
G0: microcontroller.Pin = ...
B0: microcontroller.Pin = ...
R1: microcontroller.Pin = ...
G1: microcontroller.Pin = ...
B1: microcontroller.Pin = ...
ROW_A: microcontroller.Pin = ...
ROW_B: microcontroller.Pin = ...
ROW_C: microcontroller.Pin = ...
ROW_D: microcontroller.Pin = ...
ROW_E: microcontroller.Pin = ...
CLK: microcontroller.Pin = ...
LAT: microcontroller.Pin = ...
OE: microcontroller.Pin = ...
SW_A: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
LED_R: microcontroller.Pin = ...
LED_G: microcontroller.Pin = ...
LED_B: microcontroller.Pin = ...
INT: microcontroller.Pin = ...
GP19: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
GP20: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
GP21: microcontroller.Pin = ...
USER_SW: microcontroller.Pin = ...
GP26_A0: microcontroller.Pin = ...
GP26: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
GP27_A1: microcontroller.Pin = ...
GP27: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
GP28_A2: microcontroller.Pin = ...
GP28: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
CURRENT_SENSE: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


