from __future__ import annotations
import microcontroller
"""
board Waveshare Electronics Waveshare RP2040-LCD-1.28
https://circuitpython.org/boards/waveshare_rp2040_lcd_1_28
"""
GP0: microcontroller.Pin = ...
GP1: microcontroller.Pin = ...
GP2: microcontroller.Pin = ...
GP3: microcontroller.Pin = ...
GP4: microcontroller.Pin = ...
GP5: microcontroller.Pin = ...
IMU_SDA: microcontroller.Pin = ...
GP6: microcontroller.Pin = ...
IMU_SCL: microcontroller.Pin = ...
GP7: microcontroller.Pin = ...
LCD_DC: microcontroller.Pin = ...
GP8: microcontroller.Pin = ...
LCD_CS: microcontroller.Pin = ...
GP9: microcontroller.Pin = ...
LCD_CLK: microcontroller.Pin = ...
GP10: microcontroller.Pin = ...
LCD_DIN: microcontroller.Pin = ...
GP11: microcontroller.Pin = ...
LCD_RST: microcontroller.Pin = ...
GP12: microcontroller.Pin = ...
GP13: microcontroller.Pin = ...
GP14: microcontroller.Pin = ...
GP15: microcontroller.Pin = ...
GP16: microcontroller.Pin = ...
GP17: microcontroller.Pin = ...
GP18: microcontroller.Pin = ...
GP19: microcontroller.Pin = ...
GP20: microcontroller.Pin = ...
GP21: microcontroller.Pin = ...
GP22: microcontroller.Pin = ...
IMU_INT1: microcontroller.Pin = ...
GP23: microcontroller.Pin = ...
IMU_INT2: microcontroller.Pin = ...
GP24: microcontroller.Pin = ...
LCD_BL: microcontroller.Pin = ...
GP25: microcontroller.Pin = ...
GP26_A0: microcontroller.Pin = ...
GP26: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
GP27_A1: microcontroller.Pin = ...
GP27: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
GP28_A2: microcontroller.Pin = ...
GP28: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
BAT_ADC: microcontroller.Pin = ...
