from __future__ import annotations
import microcontroller
import typing
"""
board m5stack_atom_u
https://circuitpython.org/boards/m5stack_atom_u
"""
A25: microcontroller.Pin = ...
D25: microcontroller.Pin = ...
DAC1: microcontroller.Pin = ...
D33: microcontroller.Pin = ...
A33: microcontroller.Pin = ...
D22: microcontroller.Pin = ...
D21: microcontroller.Pin = ...
PORTA_SDA: microcontroller.Pin = ...
A26: microcontroller.Pin = ...
D26: microcontroller.Pin = ...
DAC2: microcontroller.Pin = ...
PORTA_SCL: microcontroller.Pin = ...
A32: microcontroller.Pin = ...
D32: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
BTN: microcontroller.Pin = ...
IR_LED: microcontroller.Pin = ...
PDM_MIC_CLK: microcontroller.Pin = ...
PDM_MIC_DATA: microcontroller.Pin = ...
PORTA_I2C: typing.Any = ...
