from __future__ import annotations
import busio
import microcontroller
"""
board ARAMCON Badge Team ARAMCON2 Badge
https://circuitpython.org/boards/aramcon2_badge
"""
UP_BUTTON: microcontroller.Pin = ...
LEFT_BUTTON: microcontroller.Pin = ...
DOWN_BUTTON: microcontroller.Pin = ...
RIGHT_BUTTON: microcontroller.Pin = ...
ACTION_BUTTON: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
GPIO1: microcontroller.Pin = ...
GPIO2: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
DISP_BUSY: microcontroller.Pin = ...
DISP_CS: microcontroller.Pin = ...
DISP_DC: microcontroller.Pin = ...
DISP_RESET: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
VIBRATION_MOTOR: microcontroller.Pin = ...
BATTERY_SENSE: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


