from __future__ import annotations
import microcontroller
"""
board makerdiary nRF52840-MDK-Dongle
https://circuitpython.org/boards/makerdiary_nrf52840_mdk_usb_dongle
"""
AIN0: microcontroller.Pin = ...
AIN1: microcontroller.Pin = ...
AIN2: microcontroller.Pin = ...
AIN3: microcontroller.Pin = ...
AREF: microcontroller.Pin = ...
VDIV: microcontroller.Pin = ...
NFC1: microcontroller.Pin = ...
NFC2: microcontroller.Pin = ...
P2: microcontroller.Pin = ...
P3: microcontroller.Pin = ...
P4: microcontroller.Pin = ...
P5: microcontroller.Pin = ...
P6: microcontroller.Pin = ...
P7: microcontroller.Pin = ...
P8: microcontroller.Pin = ...
P9: microcontroller.Pin = ...
P10: microcontroller.Pin = ...
P18: microcontroller.Pin = ...
P19: microcontroller.Pin = ...
P20: microcontroller.Pin = ...
P21: microcontroller.Pin = ...
P22: microcontroller.Pin = ...
P23: microcontroller.Pin = ...
P24: microcontroller.Pin = ...
LED_RED: microcontroller.Pin = ...
LED_GREEN: microcontroller.Pin = ...
LED_BLUE: microcontroller.Pin = ...
BUTTON: microcontroller.Pin = ...
