from __future__ import annotations
import microcontroller
"""
board Nordic Semiconductor PCA10059
https://circuitpython.org/boards/pca10059
"""
P0_02: microcontroller.Pin = ...
P0_04: microcontroller.Pin = ...
P0_05: microcontroller.Pin = ...
P0_09: microcontroller.Pin = ...
P0_10: microcontroller.Pin = ...
P0_11: microcontroller.Pin = ...
P0_13: microcontroller.Pin = ...
P0_14: microcontroller.Pin = ...
P0_15: microcontroller.Pin = ...
P0_17: microcontroller.Pin = ...
P0_20: microcontroller.Pin = ...
P0_22: microcontroller.Pin = ...
P0_24: microcontroller.Pin = ...
P0_26: microcontroller.Pin = ...
P0_29: microcontroller.Pin = ...
P0_31: microcontroller.Pin = ...
P1_00: microcontroller.Pin = ...
P1_01: microcontroller.Pin = ...
P1_02: microcontroller.Pin = ...
P1_04: microcontroller.Pin = ...
P1_07: microcontroller.Pin = ...
P1_10: microcontroller.Pin = ...
P1_11: microcontroller.Pin = ...
P1_13: microcontroller.Pin = ...
P1_15: microcontroller.Pin = ...
LED1: microcontroller.Pin = ...
LED2_R: microcontroller.Pin = ...
LED2_G: microcontroller.Pin = ...
LED2_B: microcontroller.Pin = ...
SW1: microcontroller.Pin = ...
