from __future__ import annotations
import busio
import microcontroller
"""
board doit_esp32_devkit_v1
https://circuitpython.org/boards/doit_esp32_devkit_v1
"""
D15: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
RX2: microcontroller.Pin = ...
TX2: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
D18: microcontroller.Pin = ...
D19: microcontroller.Pin = ...
D21: microcontroller.Pin = ...
RX0: microcontroller.Pin = ...
TX0: microcontroller.Pin = ...
D22: microcontroller.Pin = ...
D23: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
D27: microcontroller.Pin = ...
D26: microcontroller.Pin = ...
D25: microcontroller.Pin = ...
D33: microcontroller.Pin = ...
D32: microcontroller.Pin = ...
D35: microcontroller.Pin = ...
D34: microcontroller.Pin = ...
VN: microcontroller.Pin = ...
VP: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
D16: microcontroller.Pin = ...
D17: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

