from __future__ import annotations
import busio
import microcontroller
import typing
"""
board Adafruit Industries LLC BLM Badge
https://circuitpython.org/boards/blm_badge
"""
RX: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
CAP1: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
CAP2: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
CAP3: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
CAP4: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
MICROPHONE_CLOCK: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
MICROPHONE_DATA: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
LIGHT: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
L: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


