from __future__ import annotations
import microcontroller
"""
board OpenMV, LLC OpenMV-H7 R1
https://circuitpython.org/boards/openmv_h7
"""
P0: microcontroller.Pin = ...
P1: microcontroller.Pin = ...
P2: microcontroller.Pin = ...
P3: microcontroller.Pin = ...
P4: microcontroller.Pin = ...
P5: microcontroller.Pin = ...
P6: microcontroller.Pin = ...
P7: microcontroller.Pin = ...
P8: microcontroller.Pin = ...
P9: microcontroller.Pin = ...
LED1: microcontroller.Pin = ...
LED2: microcontroller.Pin = ...
LED3: microcontroller.Pin = ...
LED4: microcontroller.Pin = ...
LED_RED: microcontroller.Pin = ...
LED_GREEN: microcontroller.Pin = ...
LED_BLUE: microcontroller.Pin = ...
LED_IR: microcontroller.Pin = ...
UART1_TX: microcontroller.Pin = ...
UART1_RX: microcontroller.Pin = ...
UART3_TX: microcontroller.Pin = ...
UART3_RX: microcontroller.Pin = ...
I2C2_SCL: microcontroller.Pin = ...
I2C2_SDA: microcontroller.Pin = ...
I2C4_SCL: microcontroller.Pin = ...
I2C4_SDA: microcontroller.Pin = ...
SPI2_NSS: microcontroller.Pin = ...
SPI2_SCK: microcontroller.Pin = ...
SPI2_MISO: microcontroller.Pin = ...
SPI2_MOSI: microcontroller.Pin = ...
