from __future__ import annotations
import busio
import microcontroller
"""
board 8086 Consultancy Commander
https://circuitpython.org/boards/8086_commander
"""
D0: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
B1: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
B2: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
B3: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
B4: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
CS: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
LED1A: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
LED1B: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
LED2A: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
LED2B: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
ALERT: microcontroller.Pin = ...
D15: microcontroller.Pin = ...
LED3A: microcontroller.Pin = ...
D16: microcontroller.Pin = ...
LED3B: microcontroller.Pin = ...
D17: microcontroller.Pin = ...
LED4A: microcontroller.Pin = ...
D18: microcontroller.Pin = ...
LED4B: microcontroller.Pin = ...
D19: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D20: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

