from __future__ import annotations
import displayio
import microcontroller
"""
board LILYGO TTGO T8 ESP32-S2
https://circuitpython.org/boards/lilygo_ttgo_t8_s2_st7789
"""
IO0: microcontroller.Pin = ...
IO1: microcontroller.Pin = ...
IO2: microcontroller.Pin = ...
IO3: microcontroller.Pin = ...
IO4: microcontroller.Pin = ...
IO5: microcontroller.Pin = ...
IO6: microcontroller.Pin = ...
IO7: microcontroller.Pin = ...
IO8: microcontroller.Pin = ...
IO9: microcontroller.Pin = ...
IO11: microcontroller.Pin = ...
IO12: microcontroller.Pin = ...
IO13: microcontroller.Pin = ...
IO15: microcontroller.Pin = ...
IO16: microcontroller.Pin = ...
IO17: microcontroller.Pin = ...
IO18: microcontroller.Pin = ...
IO19: microcontroller.Pin = ...
IO20: microcontroller.Pin = ...
IO21: microcontroller.Pin = ...
IO39: microcontroller.Pin = ...
IO40: microcontroller.Pin = ...
IO41: microcontroller.Pin = ...
IO42: microcontroller.Pin = ...
IO45: microcontroller.Pin = ...
IO46: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
TX1: microcontroller.Pin = ...
RX1: microcontroller.Pin = ...
SD_MISO: microcontroller.Pin = ...
SD_MOSI: microcontroller.Pin = ...
SD_CLK: microcontroller.Pin = ...
SD_CS: microcontroller.Pin = ...
LCD_MOSI: microcontroller.Pin = ...
LCD_CLK: microcontroller.Pin = ...
LCD_CS: microcontroller.Pin = ...
LCD_RST: microcontroller.Pin = ...
LCD_BCKL: microcontroller.Pin = ...
LCD_D_C: microcontroller.Pin = ...
DISPLAY: displayio.Display = ...
PE_POWER: microcontroller.Pin = ...
BATTERY: microcontroller.Pin = ...
