from __future__ import annotations
import busio
import displayio
import microcontroller
"""
board Pimoroni PicoSystem
https://circuitpython.org/boards/pimoroni_picosystem
"""
TX: microcontroller.Pin = ...
GP0: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
GP1: microcontroller.Pin = ...
VBUS_DETECT: microcontroller.Pin = ...
LCD_RESET: microcontroller.Pin = ...
LCD_CS: microcontroller.Pin = ...
LCD_SCLK: microcontroller.Pin = ...
LCD_MOSI: microcontroller.Pin = ...
LCD_VSYNC: microcontroller.Pin = ...
LCD_DC: microcontroller.Pin = ...
AUDIO: microcontroller.Pin = ...
BACKLIGHT: microcontroller.Pin = ...
LED_G: microcontroller.Pin = ...
LED_R: microcontroller.Pin = ...
LED_B: microcontroller.Pin = ...
SW_Y: microcontroller.Pin = ...
SW_X: microcontroller.Pin = ...
SW_A: microcontroller.Pin = ...
SW_B: microcontroller.Pin = ...
SW_DOWN: microcontroller.Pin = ...
SW_RIGHT: microcontroller.Pin = ...
SW_LEFT: microcontroller.Pin = ...
SW_UP: microcontroller.Pin = ...
CHARGE_STAT: microcontroller.Pin = ...
BAT_SENSE: microcontroller.Pin = ...
DISPLAY: displayio.Display = ...
def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

