from __future__ import annotations
import busio
import microcontroller
"""
board lilygo_ttgo_t-01c3
https://circuitpython.org/boards/lilygo_ttgo_t-01c3
"""
IO2: microcontroller.Pin = ...
IO8: microcontroller.Pin = ...
IO9: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
IO20: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
IO21: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
IO3: microcontroller.Pin = ...
def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

