from __future__ import annotations
import displayio
import microcontroller
"""
board Espressif ESP32-S3-Box-2.5
https://circuitpython.org/boards/espressif_esp32s3_box
"""
G9: microcontroller.Pin = ...
U0TXD: microcontroller.Pin = ...
G43: microcontroller.Pin = ...
U0RXD: microcontroller.Pin = ...
G44: microcontroller.Pin = ...
CS: microcontroller.Pin = ...
G10: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
G11: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
G13: microcontroller.Pin = ...
CLK: microcontroller.Pin = ...
G12: microcontroller.Pin = ...
G14: microcontroller.Pin = ...
G38: microcontroller.Pin = ...
G39: microcontroller.Pin = ...
SCL2: microcontroller.Pin = ...
G40: microcontroller.Pin = ...
SDA2: microcontroller.Pin = ...
G41: microcontroller.Pin = ...
G42: microcontroller.Pin = ...
G21: microcontroller.Pin = ...
LCD_DC: microcontroller.Pin = ...
LCD_CS: microcontroller.Pin = ...
LCD_MOSI: microcontroller.Pin = ...
LCD_SCK: microcontroller.Pin = ...
LCD_RST: microcontroller.Pin = ...
LCD_CTRL: microcontroller.Pin = ...
CTP_INT: microcontroller.Pin = ...
I2S_ADC_SDOUT: microcontroller.Pin = ...
I2S_MCLK: microcontroller.Pin = ...
I2S_SCLK: microcontroller.Pin = ...
I2S_LRCK: microcontroller.Pin = ...
I2S_CODEC_DSDIN: microcontroller.Pin = ...
PA_CTRL: microcontroller.Pin = ...
MUTE_STATUS: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
BOOT: microcontroller.Pin = ...
DISPLAY: displayio.Display = ...
