from __future__ import annotations
import busio
import microcontroller
import typing
"""
board m5stack_timer_camera_x
https://circuitpython.org/boards/m5stack_timer_camera_x
"""
LED: microcontroller.Pin = ...
G4: microcontroller.Pin = ...
G13: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
BAT_HOLD: microcontroller.Pin = ...
BAT_ADC: microcontroller.Pin = ...
BM8563_SCL: microcontroller.Pin = ...
BM8563_SDA: microcontroller.Pin = ...
BM8563_I2C: typing.Any = ...
VSYNC: microcontroller.Pin = ...
HREF: microcontroller.Pin = ...
PCLK: microcontroller.Pin = ...
XCLK: microcontroller.Pin = ...
RESET: microcontroller.Pin = ...
SSCB_SDA: microcontroller.Pin = ...
SSCB_SCL: microcontroller.Pin = ...
SSCB_I2C: typing.Any = ...
D: typing.Any = ...
D9: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


