from __future__ import annotations
import microcontroller
"""
board Cytron Maker Pi RP2040
https://circuitpython.org/boards/cytron_maker_pi_rp2040
"""
LED: microcontroller.Pin = ...
GP0: microcontroller.Pin = ...
GP1: microcontroller.Pin = ...
GP2: microcontroller.Pin = ...
GP3: microcontroller.Pin = ...
GP4: microcontroller.Pin = ...
GP5: microcontroller.Pin = ...
GP6: microcontroller.Pin = ...
GP7: microcontroller.Pin = ...
M1A: microcontroller.Pin = ...
GP8: microcontroller.Pin = ...
M1B: microcontroller.Pin = ...
GP9: microcontroller.Pin = ...
M2A: microcontroller.Pin = ...
GP10: microcontroller.Pin = ...
M2B: microcontroller.Pin = ...
GP11: microcontroller.Pin = ...
GP12: microcontroller.Pin = ...
GP13: microcontroller.Pin = ...
GP14: microcontroller.Pin = ...
GP15: microcontroller.Pin = ...
GP16: microcontroller.Pin = ...
GP17: microcontroller.Pin = ...
RGB: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
GP18: microcontroller.Pin = ...
GP19: microcontroller.Pin = ...
GP20: microcontroller.Pin = ...
GP21: microcontroller.Pin = ...
BUZZER: microcontroller.Pin = ...
GP22: microcontroller.Pin = ...
GP26_A0: microcontroller.Pin = ...
GP26: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
GP27_A1: microcontroller.Pin = ...
GP27: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
GP28_A2: microcontroller.Pin = ...
GP28: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
VBATT: microcontroller.Pin = ...
VOLTAGE_MONITOR: microcontroller.Pin = ...
