from __future__ import annotations
import busio
import displayio
import microcontroller
import typing
"""
board Adafruit FunHouse
https://circuitpython.org/boards/adafruit_funhouse
"""
TFT_BACKLIGHT: microcontroller.Pin = ...
TFT_CS: microcontroller.Pin = ...
TFT_DC: microcontroller.Pin = ...
TFT_MOSI: microcontroller.Pin = ...
TFT_RESET: microcontroller.Pin = ...
TFT_SCK: microcontroller.Pin = ...
BUTTON_DOWN: microcontroller.Pin = ...
BUTTON_SELECT: microcontroller.Pin = ...
BUTTON_UP: microcontroller.Pin = ...
CAP6: microcontroller.Pin = ...
CAP7: microcontroller.Pin = ...
CAP8: microcontroller.Pin = ...
CAP9: microcontroller.Pin = ...
CAP10: microcontroller.Pin = ...
CAP11: microcontroller.Pin = ...
CAP12: microcontroller.Pin = ...
CAP13: microcontroller.Pin = ...
DOTSTAR_DATA: microcontroller.Pin = ...
DOTSTAR_CLOCK: microcontroller.Pin = ...
PIR_SENSE: microcontroller.Pin = ...
LIGHT: microcontroller.Pin = ...
SPEAKER: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
DISPLAY: displayio.Display = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


