from __future__ import annotations
import busio
import microcontroller
"""
board Seeed Seeed XIAO nRF52840 Sense
https://circuitpython.org/boards/Seeed_XIAO_nRF52840_Sense
"""
A0: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
NFC1: microcontroller.Pin = ...
NFC2: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
LED_RED: microcontroller.Pin = ...
LED_BLUE: microcontroller.Pin = ...
LED_GREEN: microcontroller.Pin = ...
IMU_PWR: microcontroller.Pin = ...
IMU_SCL: microcontroller.Pin = ...
IMU_SDA: microcontroller.Pin = ...
IMU_INT1: microcontroller.Pin = ...
MIC_PWR: microcontroller.Pin = ...
PDM_CLK: microcontroller.Pin = ...
PDM_DATA: microcontroller.Pin = ...
READ_BATT_ENABLE: microcontroller.Pin = ...
VBATT: microcontroller.Pin = ...
CHARGE_STATUS: microcontroller.Pin = ...
CHARGE_RATE: microcontroller.Pin = ...
def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


