from __future__ import annotations
import busio
import microcontroller
import typing
"""
board Datanoise PicoADK
https://circuitpython.org/boards/datanoise_picoadk
"""
SCK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
ADC_SCK: microcontroller.Pin = ...
ADC_MOSI: microcontroller.Pin = ...
ADC_MISO: microcontroller.Pin = ...
ADC_CS: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
D29: microcontroller.Pin = ...
D19: microcontroller.Pin = ...
D20: microcontroller.Pin = ...
D21: microcontroller.Pin = ...
D22: microcontroller.Pin = ...
D26: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
I2S_DOUT: microcontroller.Pin = ...
I2S_BCLK: microcontroller.Pin = ...
I2S_LRCLK: microcontroller.Pin = ...
I2S_DEMP: microcontroller.Pin = ...
I2S_XSMT: microcontroller.Pin = ...
VBUS_SENSE: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

