from __future__ import annotations
import displayio
import microcontroller
import typing
"""
board Kittenbot Meowbit
https://circuitpython.org/boards/meowbit_v121
"""
LED_RED: microcontroller.Pin = ...
LED_GREEN: microcontroller.Pin = ...
DISP_SCK: microcontroller.Pin = ...
DISP_MISO: microcontroller.Pin = ...
DISP_MOSI: microcontroller.Pin = ...
DISP_CS: microcontroller.Pin = ...
DISP_DC: microcontroller.Pin = ...
DISP_RST: microcontroller.Pin = ...
DISP_BL: microcontroller.Pin = ...
BUZZ: typing.Any = ...
BTNA: microcontroller.Pin = ...
BTNB: microcontroller.Pin = ...
RIGHT: microcontroller.Pin = ...
DOWN: microcontroller.Pin = ...
LEFT: microcontroller.Pin = ...
TEMP: microcontroller.Pin = ...
UP: microcontroller.Pin = ...
LIGHT: microcontroller.Pin = ...
MENU: microcontroller.Pin = ...
JACK_TX: microcontroller.Pin = ...
JACK_PWREN: microcontroller.Pin = ...
JACK_SND: microcontroller.Pin = ...
ACC_INT: microcontroller.Pin = ...
ACC_SCL: microcontroller.Pin = ...
ACC_SDA: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
NSS: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
P20: microcontroller.Pin = ...
P19: microcontroller.Pin = ...
P16: microcontroller.Pin = ...
P15: microcontroller.Pin = ...
P14: microcontroller.Pin = ...
P13: microcontroller.Pin = ...
P2: microcontroller.Pin = ...
P12: microcontroller.Pin = ...
P11: microcontroller.Pin = ...
P10: microcontroller.Pin = ...
P9: microcontroller.Pin = ...
P8: microcontroller.Pin = ...
P1: microcontroller.Pin = ...
P7: microcontroller.Pin = ...
P6: microcontroller.Pin = ...
P5: microcontroller.Pin = ...
P4: microcontroller.Pin = ...
P0: microcontroller.Pin = ...
P3: microcontroller.Pin = ...
DISPLAY: displayio.Display = ...
INTERNAL_SPI: typing.Any = ...
