from __future__ import annotations
import microcontroller
"""
board Waveshare Electronics ESP32-S2-Pico
https://circuitpython.org/boards/waveshare_esp32s2_pico
"""
BUTTON: microcontroller.Pin = ...
BOOT0: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
GP0: microcontroller.Pin = ...
GP2: microcontroller.Pin = ...
GP3: microcontroller.Pin = ...
GP4: microcontroller.Pin = ...
GP5: microcontroller.Pin = ...
GP6: microcontroller.Pin = ...
GP7: microcontroller.Pin = ...
GP8: microcontroller.Pin = ...
GP10: microcontroller.Pin = ...
GP11: microcontroller.Pin = ...
GP12: microcontroller.Pin = ...
GP13: microcontroller.Pin = ...
GP14: microcontroller.Pin = ...
GP15: microcontroller.Pin = ...
GP16: microcontroller.Pin = ...
GP17: microcontroller.Pin = ...
GP34: microcontroller.Pin = ...
GP35: microcontroller.Pin = ...
GP36: microcontroller.Pin = ...
GP37: microcontroller.Pin = ...
GP38: microcontroller.Pin = ...
GP39: microcontroller.Pin = ...
GP40: microcontroller.Pin = ...
GP41: microcontroller.Pin = ...
GP42: microcontroller.Pin = ...
GP43: microcontroller.Pin = ...
GP44: microcontroller.Pin = ...
