from __future__ import annotations
import busio
import microcontroller
"""
board BHDynamics DynaLoRa_USB
https://circuitpython.org/boards/dynalora_usb
"""
D0: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
RADIO_CS: microcontroller.Pin = ...
RADIO_INT: microcontroller.Pin = ...
RADIO_RESET: microcontroller.Pin = ...
SD_CS: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
MOSI1: microcontroller.Pin = ...
MISO1: microcontroller.Pin = ...
SCK1: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
BUTTON: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

