from __future__ import annotations
import microcontroller
"""
board Adafruit Industries LLC Rotary Trinkey M0
https://circuitpython.org/boards/adafruit_rotary_trinkey_m0
"""
NEOPIXEL: microcontroller.Pin = ...
ROTA: microcontroller.Pin = ...
ROTB: microcontroller.Pin = ...
SWITCH: microcontroller.Pin = ...
TOUCH: microcontroller.Pin = ...
