from __future__ import annotations
import busio
import microcontroller
import typing
"""
board Adafruit Feather RP2040 RFM
https://circuitpython.org/boards/adafruit_feather_rp2040_rfm
"""
A0: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
D24: microcontroller.Pin = ...
D25: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
BUTTON: microcontroller.Pin = ...
BOOT: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
RFM_CS: microcontroller.Pin = ...
RFM_RST: microcontroller.Pin = ...
RFM_IO5: microcontroller.Pin = ...
RFM_IO3: microcontroller.Pin = ...
RFM_IO4: microcontroller.Pin = ...
RFM_IO0: microcontroller.Pin = ...
RFM_IO1: microcontroller.Pin = ...
RFM_IO2: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

