from __future__ import annotations
import microcontroller
"""
board adafruit_huzzah32_breakout
https://circuitpython.org/boards/adafruit_huzzah32_breakout
"""
IO0: microcontroller.Pin = ...
BUTTON: microcontroller.Pin = ...
IO1: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
IO2: microcontroller.Pin = ...
IO3: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
IO4: microcontroller.Pin = ...
IO5: microcontroller.Pin = ...
IO12: microcontroller.Pin = ...
IO13: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
IO14: microcontroller.Pin = ...
IO15: microcontroller.Pin = ...
IO16: microcontroller.Pin = ...
IO17: microcontroller.Pin = ...
IO18: microcontroller.Pin = ...
IO19: microcontroller.Pin = ...
IO21: microcontroller.Pin = ...
IO22: microcontroller.Pin = ...
IO23: microcontroller.Pin = ...
IO25: microcontroller.Pin = ...
IO26: microcontroller.Pin = ...
IO27: microcontroller.Pin = ...
IO32: microcontroller.Pin = ...
IO33: microcontroller.Pin = ...
IO34: microcontroller.Pin = ...
IO35: microcontroller.Pin = ...
IO36: microcontroller.Pin = ...
IO39: microcontroller.Pin = ...
