from __future__ import annotations
import busio
import microcontroller
import typing
"""
board M5Stack M5Stack AtomS3 Lite
https://circuitpython.org/boards/m5stack_atoms3_lite
"""
PORTA_SCL: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
PORTA_SDA: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
A6: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
A7: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
D39: microcontroller.Pin = ...
D38: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
BTN: microcontroller.Pin = ...
IR_LED: microcontroller.Pin = ...
PORTA_I2C: typing.Any = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


