from __future__ import annotations
import busio
import microcontroller
"""
board Particle Xenon
https://circuitpython.org/boards/particle_xenon
"""
A0: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
MODE: microcontroller.Pin = ...
VOLTAGE_MONITOR: microcontroller.Pin = ...
BATTERY: microcontroller.Pin = ...
CHARGE_STATUS: microcontroller.Pin = ...
NFC1: microcontroller.Pin = ...
NFC2: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
BLUE_LED: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
RGB_LED_RED: microcontroller.Pin = ...
RGB_LED_GREEN: microcontroller.Pin = ...
RGB_LED_BLUE: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
ANTENNA_EXTERNAL: microcontroller.Pin = ...
ANTENNA_PCB: microcontroller.Pin = ...
def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


