from __future__ import annotations
import displayio
import microcontroller
"""
board Waveshare Electronics Waveshare RP2040-LCD-0.96
https://circuitpython.org/boards/waveshare_rp2040_lcd_0_96
"""
GP0: microcontroller.Pin = ...
GP1: microcontroller.Pin = ...
GP2: microcontroller.Pin = ...
GP3: microcontroller.Pin = ...
GP4: microcontroller.Pin = ...
GP5: microcontroller.Pin = ...
GP6: microcontroller.Pin = ...
GP7: microcontroller.Pin = ...
GP8: microcontroller.Pin = ...
GP9: microcontroller.Pin = ...
GP10: microcontroller.Pin = ...
GP11: microcontroller.Pin = ...
GP12: microcontroller.Pin = ...
GP13: microcontroller.Pin = ...
GP14: microcontroller.Pin = ...
GP15: microcontroller.Pin = ...
GP16: microcontroller.Pin = ...
GP17: microcontroller.Pin = ...
GP18: microcontroller.Pin = ...
GP19: microcontroller.Pin = ...
GP20: microcontroller.Pin = ...
GP21: microcontroller.Pin = ...
GP22: microcontroller.Pin = ...
GP25: microcontroller.Pin = ...
GP26: microcontroller.Pin = ...
GP27: microcontroller.Pin = ...
GP28: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
GP26_A0: microcontroller.Pin = ...
GP27_A1: microcontroller.Pin = ...
GP28_A2: microcontroller.Pin = ...
LCD_DC: microcontroller.Pin = ...
LCD_CS: microcontroller.Pin = ...
LCD_CLK: microcontroller.Pin = ...
LCD_DIN: microcontroller.Pin = ...
LCD_RST: microcontroller.Pin = ...
LCD_BL: microcontroller.Pin = ...
DISPLAY: displayio.Display = ...
SMPS_MODE: microcontroller.Pin = ...
VBUS_SENSE: microcontroller.Pin = ...
VOLTAGE_MONITOR: microcontroller.Pin = ...
