from __future__ import annotations
import busio
import microcontroller
"""
board George Robotic Pyboard Version 1.1
https://circuitpython.org/boards/pyboard_v11
"""
Y1: microcontroller.Pin = ...
Y2: microcontroller.Pin = ...
Y3: microcontroller.Pin = ...
Y4: microcontroller.Pin = ...
Y5: microcontroller.Pin = ...
Y6: microcontroller.Pin = ...
Y7: microcontroller.Pin = ...
Y8: microcontroller.Pin = ...
Y9: microcontroller.Pin = ...
Y10: microcontroller.Pin = ...
Y11: microcontroller.Pin = ...
Y12: microcontroller.Pin = ...
X1: microcontroller.Pin = ...
X2: microcontroller.Pin = ...
X3: microcontroller.Pin = ...
X4: microcontroller.Pin = ...
X5: microcontroller.Pin = ...
X6: microcontroller.Pin = ...
X7: microcontroller.Pin = ...
X8: microcontroller.Pin = ...
X9: microcontroller.Pin = ...
X10: microcontroller.Pin = ...
X11: microcontroller.Pin = ...
X12: microcontroller.Pin = ...
X17: microcontroller.Pin = ...
X18: microcontroller.Pin = ...
X19: microcontroller.Pin = ...
X20: microcontroller.Pin = ...
X21: microcontroller.Pin = ...
X22: microcontroller.Pin = ...
P2: microcontroller.Pin = ...
P3: microcontroller.Pin = ...
P4: microcontroller.Pin = ...
P5: microcontroller.Pin = ...
LED1: microcontroller.Pin = ...
LED2: microcontroller.Pin = ...
LED3: microcontroller.Pin = ...
LED4: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


