from __future__ import annotations
import microcontroller
"""
board Artisense Reference Design RD00
https://circuitpython.org/boards/artisense_rd00
"""
IO0: microcontroller.Pin = ...
IO1: microcontroller.Pin = ...
IO2: microcontroller.Pin = ...
IO3: microcontroller.Pin = ...
IO4: microcontroller.Pin = ...
CAM: microcontroller.Pin = ...
HVIO0: microcontroller.Pin = ...
HVIO1: microcontroller.Pin = ...
HVIO2: microcontroller.Pin = ...
HVIO3: microcontroller.Pin = ...
HVIO4: microcontroller.Pin = ...
HVCAM: microcontroller.Pin = ...
LVIO0: microcontroller.Pin = ...
LVIO1: microcontroller.Pin = ...
LVIO2: microcontroller.Pin = ...
LVIO3: microcontroller.Pin = ...
LVIO4: microcontroller.Pin = ...
LVCAM: microcontroller.Pin = ...
DIRIO0: microcontroller.Pin = ...
DIRIO1: microcontroller.Pin = ...
DIRIO2: microcontroller.Pin = ...
DIRIO3: microcontroller.Pin = ...
DIRIO4: microcontroller.Pin = ...
DIRCAM: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
DBG_TX: microcontroller.Pin = ...
DBG_RX: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
RS232_TX: microcontroller.Pin = ...
RS232_RX: microcontroller.Pin = ...
RS232_EN: microcontroller.Pin = ...
DFU: microcontroller.Pin = ...
SW1: microcontroller.Pin = ...
BOOT: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
