from __future__ import annotations
import busio
import displayio
import microcontroller
"""
board hardkernel_odroid_go
https://circuitpython.org/boards/hardkernel_odroid_go
"""
BATTERY: microcontroller.Pin = ...
BTN_START: microcontroller.Pin = ...
BTN_AXIS_X: microcontroller.Pin = ...
BTN_AXIS_Y: microcontroller.Pin = ...
BTN_A: microcontroller.Pin = ...
BTN_B: microcontroller.Pin = ...
SPEAKER_IN_M: microcontroller.Pin = ...
SPEAKER_IN_P: microcontroller.Pin = ...
BTN_SELECT: microcontroller.Pin = ...
BACKLIGHT_PWM: microcontroller.Pin = ...
EXT3: microcontroller.Pin = ...
BTN_MENU: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
EXT8: microcontroller.Pin = ...
SD_CS: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
EXT7: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
EXT2: microcontroller.Pin = ...
LCD_CS: microcontroller.Pin = ...
EXT5: microcontroller.Pin = ...
BTN_VOLUME: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
EXT4: microcontroller.Pin = ...
DISPLAY: displayio.Display = ...
def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


