from __future__ import annotations
import microcontroller
"""
board MicroPython Chinese Community PYB LR Nano V2
https://circuitpython.org/boards/pyb_nano_v2
"""
Y10: microcontroller.Pin = ...
Y9: microcontroller.Pin = ...
Y8: microcontroller.Pin = ...
Y7: microcontroller.Pin = ...
Y6: microcontroller.Pin = ...
Y5: microcontroller.Pin = ...
Y4: microcontroller.Pin = ...
Y3: microcontroller.Pin = ...
Y2: microcontroller.Pin = ...
Y1: microcontroller.Pin = ...
Y0: microcontroller.Pin = ...
X15: microcontroller.Pin = ...
X14: microcontroller.Pin = ...
X13: microcontroller.Pin = ...
X12: microcontroller.Pin = ...
X11: microcontroller.Pin = ...
X10: microcontroller.Pin = ...
X9: microcontroller.Pin = ...
X8: microcontroller.Pin = ...
X7: microcontroller.Pin = ...
X6: microcontroller.Pin = ...
X5: microcontroller.Pin = ...
X4: microcontroller.Pin = ...
X3: microcontroller.Pin = ...
X2: microcontroller.Pin = ...
X1: microcontroller.Pin = ...
X0: microcontroller.Pin = ...
SDA1: microcontroller.Pin = ...
SCL1: microcontroller.Pin = ...
SDA2: microcontroller.Pin = ...
SCL2: microcontroller.Pin = ...
SDA3: microcontroller.Pin = ...
SCL3: microcontroller.Pin = ...
SCK1: microcontroller.Pin = ...
MISO1: microcontroller.Pin = ...
MOSI1: microcontroller.Pin = ...
SCK2: microcontroller.Pin = ...
MISO2: microcontroller.Pin = ...
MOSI2: microcontroller.Pin = ...
TX1: microcontroller.Pin = ...
RX1: microcontroller.Pin = ...
TX2: microcontroller.Pin = ...
RX2: microcontroller.Pin = ...
LED_RED: microcontroller.Pin = ...
LED_GREEN: microcontroller.Pin = ...
LED_YELLOW: microcontroller.Pin = ...
LED_BLUE: microcontroller.Pin = ...
SW: microcontroller.Pin = ...
