from __future__ import annotations
import busio
import displayio
import microcontroller
import typing
"""
board lilygo_twatch_2020_v3
https://circuitpython.org/boards/lilygo_twatch_2020_v3
"""
VIBRATE: microcontroller.Pin = ...
I2S_SCK: microcontroller.Pin = ...
I2S_WS: microcontroller.Pin = ...
I2S_OUT: microcontroller.Pin = ...
PDM_CLK: microcontroller.Pin = ...
PDM_DATA: microcontroller.Pin = ...
IR_LED: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
BMA423_INT: microcontroller.Pin = ...
PCF8563_INT: microcontroller.Pin = ...
AXP202_INT: microcontroller.Pin = ...
TOUCH_SCL: microcontroller.Pin = ...
TOUCH_SDA: microcontroller.Pin = ...
TOUCH_RST: microcontroller.Pin = ...
TOUCH_INT: microcontroller.Pin = ...
TOUCH_I2C: typing.Any = ...
LCD_CLK: microcontroller.Pin = ...
LCD_MOSI: microcontroller.Pin = ...
LCD_DC: microcontroller.Pin = ...
LCD_CS: microcontroller.Pin = ...
LCD_BRIGHTNESS: microcontroller.Pin = ...
LCD_SPI: typing.Any = ...
DISPLAY: displayio.Display = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


