from __future__ import annotations
import busio
import microcontroller
"""
board Solder Party BBQ20 Keyboard
https://circuitpython.org/boards/solderparty_bbq20kbd
"""
INT: microcontroller.Pin = ...
PERIPHERAL_SDA: microcontroller.Pin = ...
PERIPHERAL_SCL: microcontroller.Pin = ...
ROW1: microcontroller.Pin = ...
ROW2: microcontroller.Pin = ...
ROW3: microcontroller.Pin = ...
ROW4: microcontroller.Pin = ...
ROW5: microcontroller.Pin = ...
ROW6: microcontroller.Pin = ...
ROW7: microcontroller.Pin = ...
COL1: microcontroller.Pin = ...
COL2: microcontroller.Pin = ...
COL3: microcontroller.Pin = ...
COL4: microcontroller.Pin = ...
COL5: microcontroller.Pin = ...
COL6: microcontroller.Pin = ...
BTN1: microcontroller.Pin = ...
BACKLIGHT: microcontroller.Pin = ...
TP_RESET: microcontroller.Pin = ...
TP_MOTION: microcontroller.Pin = ...
TP_SHUTDOWN: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

