from __future__ import annotations
import busio
import microcontroller
"""
board Silicognition LLC M4-Shim
https://circuitpython.org/boards/silicognition-m4-shim
"""
A0: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
D15: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
D16: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
D17: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
D18: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
D19: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
D25: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
D24: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
D23: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

