from __future__ import annotations
import displayio
import microcontroller
import typing
"""
board m5stack_stick_c
https://circuitpython.org/boards/m5stack_stick_c
"""
A26: microcontroller.Pin = ...
D26: microcontroller.Pin = ...
A36: microcontroller.Pin = ...
D36: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
PORTA_SDA: microcontroller.Pin = ...
D32: microcontroller.Pin = ...
PORTA_SCL: microcontroller.Pin = ...
D33: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
IR_LED: microcontroller.Pin = ...
BTN_A: microcontroller.Pin = ...
BTN_B: microcontroller.Pin = ...
SYS_SDA: microcontroller.Pin = ...
SYS_SCL: microcontroller.Pin = ...
SYS_INT: microcontroller.Pin = ...
PMU_N_VBUSEN: microcontroller.Pin = ...
PDM_MIC_CLK: microcontroller.Pin = ...
PDM_MIC_DATA: microcontroller.Pin = ...
LCD_MOSI: microcontroller.Pin = ...
LCD_CLK: microcontroller.Pin = ...
LCD_DC: microcontroller.Pin = ...
LCD_RST: microcontroller.Pin = ...
LCD_CS: microcontroller.Pin = ...
SYS_I2C: typing.Any = ...
PORTA_I2C: typing.Any = ...
DISPLAY: displayio.Display = ...
