from __future__ import annotations
import microcontroller
"""
board AtelierDuMaker ADM_B_NRF52840_1
https://circuitpython.org/boards/ADM_B_NRF52840_1
"""
P1_10: microcontroller.Pin = ...
P1_11: microcontroller.Pin = ...
P1_13: microcontroller.Pin = ...
P1_15: microcontroller.Pin = ...
P0_03: microcontroller.Pin = ...
P0_02: microcontroller.Pin = ...
P0_28: microcontroller.Pin = ...
P0_29: microcontroller.Pin = ...
P0_30: microcontroller.Pin = ...
P0_31: microcontroller.Pin = ...
P0_04: microcontroller.Pin = ...
P0_05: microcontroller.Pin = ...
P1_14: microcontroller.Pin = ...
P1_12: microcontroller.Pin = ...
P0_25: microcontroller.Pin = ...
P0_11: microcontroller.Pin = ...
P1_08: microcontroller.Pin = ...
P0_27: microcontroller.Pin = ...
P0_08: microcontroller.Pin = ...
P0_06: microcontroller.Pin = ...
P0_26: microcontroller.Pin = ...
P0_10: microcontroller.Pin = ...
P0_09: microcontroller.Pin = ...
P1_06: microcontroller.Pin = ...
P1_04: microcontroller.Pin = ...
P1_02: microcontroller.Pin = ...
P1_01: microcontroller.Pin = ...
P1_03: microcontroller.Pin = ...
P1_00: microcontroller.Pin = ...
P0_22: microcontroller.Pin = ...
P1_07: microcontroller.Pin = ...
P1_05: microcontroller.Pin = ...
P0_24: microcontroller.Pin = ...
P0_20: microcontroller.Pin = ...
P0_17: microcontroller.Pin = ...
P0_15: microcontroller.Pin = ...
P0_14: microcontroller.Pin = ...
P0_13: microcontroller.Pin = ...
P0_16: microcontroller.Pin = ...
P0_07: microcontroller.Pin = ...
P1_09: microcontroller.Pin = ...
P0_12: microcontroller.Pin = ...
P0_23: microcontroller.Pin = ...
P0_21: microcontroller.Pin = ...
P0_19: microcontroller.Pin = ...
