from __future__ import annotations
import busio
import microcontroller
"""
board maholli kicksat-sprite
https://circuitpython.org/boards/kicksat-sprite
"""
SCK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
radioCS: microcontroller.Pin = ...
WAKE: microcontroller.Pin = ...
SHDWN: microcontroller.Pin = ...
PWDWN: microcontroller.Pin = ...
TST: microcontroller.Pin = ...
FSYNC: microcontroller.Pin = ...
VCLK: microcontroller.Pin = ...
FSYNC: microcontroller.Pin = ...
MD: microcontroller.Pin = ...
MC: microcontroller.Pin = ...
PA08: microcontroller.Pin = ...
PA10: microcontroller.Pin = ...
PA09: microcontroller.Pin = ...
PA06: microcontroller.Pin = ...
DAC0: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


