from __future__ import annotations
import microcontroller
"""
board ZRichard RP2.65-F
https://circuitpython.org/boards/zrichard_rp2
"""
ROW0: microcontroller.Pin = ...
COL0: microcontroller.Pin = ...
ROW1: microcontroller.Pin = ...
COL1: microcontroller.Pin = ...
ROW2: microcontroller.Pin = ...
COL2: microcontroller.Pin = ...
ROW3: microcontroller.Pin = ...
COL3: microcontroller.Pin = ...
ROW4: microcontroller.Pin = ...
COL4: microcontroller.Pin = ...
ROW5: microcontroller.Pin = ...
COL5: microcontroller.Pin = ...
ROW6: microcontroller.Pin = ...
COL6: microcontroller.Pin = ...
ROW7: microcontroller.Pin = ...
COL7: microcontroller.Pin = ...
ROW8: microcontroller.Pin = ...
ROW9: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
RV1: microcontroller.Pin = ...
RV2: microcontroller.Pin = ...
RV3: microcontroller.Pin = ...
