from __future__ import annotations
import busio
import microcontroller
import typing
"""
board deneyap_kart_g
https://circuitpython.org/boards/deneyap_kart_g
"""
RX: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
GPKEY: microcontroller.Pin = ...
BT: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
RGBLED: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
SS: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
PWM0: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
PWM1: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
PWM2: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

