from __future__ import annotations
import busio
import microcontroller
import typing
"""
board Oak Development Technologies CP Sapling Rev B
https://circuitpython.org/boards/cp_sapling_m0_revb
"""
D4: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
A6: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
A7: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
A8: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
A9: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
A10: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
A11: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
A12: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
A13: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
A14: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D15: microcontroller.Pin = ...
A15: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

