from __future__ import annotations
import microcontroller
"""
board ELECFREAKS Pico:ed
https://circuitpython.org/boards/elecfreaks_picoed
"""
BUZZER_GP0: microcontroller.Pin = ...
I2C0_SDA: microcontroller.Pin = ...
I2C0_SCL: microcontroller.Pin = ...
BUZZER: microcontroller.Pin = ...
BUZZER_GP3: microcontroller.Pin = ...
P4: microcontroller.Pin = ...
P5: microcontroller.Pin = ...
P6: microcontroller.Pin = ...
P7: microcontroller.Pin = ...
P8: microcontroller.Pin = ...
P9: microcontroller.Pin = ...
P10: microcontroller.Pin = ...
P11: microcontroller.Pin = ...
P12: microcontroller.Pin = ...
P13: microcontroller.Pin = ...
P14: microcontroller.Pin = ...
P15: microcontroller.Pin = ...
P16: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
P20: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
P19: microcontroller.Pin = ...
BUTTON_A: microcontroller.Pin = ...
BUTTON_B: microcontroller.Pin = ...
SMPS_MODE: microcontroller.Pin = ...
VBUS_SENSE: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
P0_A0: microcontroller.Pin = ...
P0: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
P1_A1: microcontroller.Pin = ...
P1: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
P2_A2: microcontroller.Pin = ...
P2: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
P3_A3: microcontroller.Pin = ...
P3: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
