from __future__ import annotations
import busio
import microcontroller
"""
board Nordic Semiconductor PCA10056
https://circuitpython.org/boards/pca10056
"""
P0_00: microcontroller.Pin = ...
P0_01: microcontroller.Pin = ...
P0_02: microcontroller.Pin = ...
P0_03: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
P0_04: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
P0_05: microcontroller.Pin = ...
P0_06: microcontroller.Pin = ...
P0_07: microcontroller.Pin = ...
P0_08: microcontroller.Pin = ...
P0_09: microcontroller.Pin = ...
P0_10: microcontroller.Pin = ...
P0_11: microcontroller.Pin = ...
BUTTON1: microcontroller.Pin = ...
P0_12: microcontroller.Pin = ...
BUTTON2: microcontroller.Pin = ...
P0_13: microcontroller.Pin = ...
L: microcontroller.Pin = ...
LED1: microcontroller.Pin = ...
P0_14: microcontroller.Pin = ...
LED2: microcontroller.Pin = ...
P0_15: microcontroller.Pin = ...
LED3: microcontroller.Pin = ...
P0_16: microcontroller.Pin = ...
LED4: microcontroller.Pin = ...
P0_17: microcontroller.Pin = ...
P0_19: microcontroller.Pin = ...
P0_20: microcontroller.Pin = ...
P0_21: microcontroller.Pin = ...
P0_22: microcontroller.Pin = ...
P0_23: microcontroller.Pin = ...
P0_24: microcontroller.Pin = ...
BUTTON3: microcontroller.Pin = ...
P0_25: microcontroller.Pin = ...
BUTTON4: microcontroller.Pin = ...
P0_26: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
P0_27: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
P0_28: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
P0_29: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
P0_30: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
P0_31: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
P1_00: microcontroller.Pin = ...
P1_01: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
P1_02: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
P1_03: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
P1_04: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
P1_05: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
P1_06: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
P1_07: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
P1_08: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
P1_09: microcontroller.Pin = ...
P1_10: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
P1_11: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
P1_12: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
P1_13: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
P1_14: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
P1_15: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

