from __future__ import annotations
import busio
import displayio
import microcontroller
"""
board OSHWA OHS2020 Badge
https://circuitpython.org/boards/ohs2020_badge
"""
MICROPHONE_CLOCK: microcontroller.Pin = ...
MICROPHONE_DATA: microcontroller.Pin = ...
TFT_RESET: microcontroller.Pin = ...
TFT_BACKLIGHT: microcontroller.Pin = ...
TFT_CS: microcontroller.Pin = ...
TFT_DC: microcontroller.Pin = ...
TFT_SCK: microcontroller.Pin = ...
TFT_MOSI: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
DISPLAY: displayio.Display = ...
BUTTON_SW1: microcontroller.Pin = ...
BUTTON_SW2: microcontroller.Pin = ...
BUTTON_SW3: microcontroller.Pin = ...
BUTTON_SW4: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


