from __future__ import annotations
import busio
import microcontroller
import typing
"""
board deneyap_kart
https://circuitpython.org/boards/deneyap_kart
"""
D0: microcontroller.Pin = ...
PWM0: microcontroller.Pin = ...
CAMD4: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
PWM1: microcontroller.Pin = ...
CAMD3: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
LEDG: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
LEDR: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
SS: microcontroller.Pin = ...
CAMD5: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
CAMD2: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
CAMD6: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
CAMPC: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
BOOT: microcontroller.Pin = ...
GPKEY: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
IMUSD: microcontroller.Pin = ...
LEDB: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
IMUSC: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
T5: microcontroller.Pin = ...
MICC: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
T4: microcontroller.Pin = ...
MICD: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
T3: microcontroller.Pin = ...
D15: microcontroller.Pin = ...
T2: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
CAMV: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
CAMH: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
CAMD9: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
CAMD8: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
T0: microcontroller.Pin = ...
CAMXC: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
T1: microcontroller.Pin = ...
CAMSD: microcontroller.Pin = ...
DAC1: microcontroller.Pin = ...
CAMSC: microcontroller.Pin = ...
DAC2: microcontroller.Pin = ...
CAMD7: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

