from __future__ import annotations
import busio
import microcontroller
"""
board unexpectedmaker_tinypico_nano
https://circuitpython.org/boards/unexpectedmaker_tinypico_nano
"""
IO0: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
IO2: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
IO4: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
IO5: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
IO9: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
IO12: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
A12: microcontroller.Pin = ...
IO13: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
A13: microcontroller.Pin = ...
IO14: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
A14: microcontroller.Pin = ...
IO15: microcontroller.Pin = ...
D15: microcontroller.Pin = ...
A15: microcontroller.Pin = ...
IO18: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
D18: microcontroller.Pin = ...
IO19: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
SDI: microcontroller.Pin = ...
D19: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
IO21: microcontroller.Pin = ...
D21: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
IO22: microcontroller.Pin = ...
D22: microcontroller.Pin = ...
IO23: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
SDO: microcontroller.Pin = ...
D23: microcontroller.Pin = ...
IO25: microcontroller.Pin = ...
D25: microcontroller.Pin = ...
A25: microcontroller.Pin = ...
DAC1: microcontroller.Pin = ...
IO26: microcontroller.Pin = ...
D26: microcontroller.Pin = ...
A26: microcontroller.Pin = ...
DAC2: microcontroller.Pin = ...
IO27: microcontroller.Pin = ...
D27: microcontroller.Pin = ...
A27: microcontroller.Pin = ...
IO32: microcontroller.Pin = ...
D32: microcontroller.Pin = ...
A32: microcontroller.Pin = ...
IO33: microcontroller.Pin = ...
D33: microcontroller.Pin = ...
A33: microcontroller.Pin = ...
IO34: microcontroller.Pin = ...
D34: microcontroller.Pin = ...
A34: microcontroller.Pin = ...
IO35: microcontroller.Pin = ...
D35: microcontroller.Pin = ...
A35: microcontroller.Pin = ...
IO36: microcontroller.Pin = ...
D36: microcontroller.Pin = ...
A36: microcontroller.Pin = ...
IO37: microcontroller.Pin = ...
D37: microcontroller.Pin = ...
A37: microcontroller.Pin = ...
IO38: microcontroller.Pin = ...
D38: microcontroller.Pin = ...
A38: microcontroller.Pin = ...
IO39: microcontroller.Pin = ...
D39: microcontroller.Pin = ...
A39: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

