from __future__ import annotations
import busio
import displayio
import microcontroller
import typing
"""
board Espressif ESP32-S3-EYE
https://circuitpython.org/boards/espressif_esp32s3_eye
"""
BOOT: microcontroller.Pin = ...
BUTTONS: microcontroller.Pin = ...
MIC_SDO: microcontroller.Pin = ...
IO3: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
CAMERA_DATA: typing.Any = ...
CAMERA_VSYNC: microcontroller.Pin = ...
CAMERA_HREF: microcontroller.Pin = ...
CAMERA_PCLK: microcontroller.Pin = ...
BATTERY: microcontroller.Pin = ...
CAMERA_XCLK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
MISO1: microcontroller.Pin = ...
MOSI1: microcontroller.Pin = ...
SCK1: microcontroller.Pin = ...
MIC_SCK: microcontroller.Pin = ...
MIC_WS: microcontroller.Pin = ...
LCD_DC: microcontroller.Pin = ...
LCD_CS: microcontroller.Pin = ...
BACKLIGHT: microcontroller.Pin = ...
DISPLAY: displayio.Display = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


