from __future__ import annotations
import microcontroller
"""
board ARAMCON Badge Team ARAMCON Badge 2019
https://circuitpython.org/boards/aramcon_badge_2019
"""
LEFT_BUTTON: microcontroller.Pin = ...
MIDDLE_BUTTON: microcontroller.Pin = ...
RIGHT_BUTTON: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
SND_CS: microcontroller.Pin = ...
SND_DREQ: microcontroller.Pin = ...
SND_RESET: microcontroller.Pin = ...
SND_XDCS: microcontroller.Pin = ...
DISP_BUSY: microcontroller.Pin = ...
DISP_CS: microcontroller.Pin = ...
DISP_DC: microcontroller.Pin = ...
DISP_RESET: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
VIBRATION_MOTOR: microcontroller.Pin = ...
BATTERY_SENSE: microcontroller.Pin = ...
