from __future__ import annotations
import busio
import displayio
import microcontroller
import typing
"""
board m5stack_m5paper
https://circuitpython.org/boards/m5stack_m5paper
"""
POWER_MAIN: microcontroller.Pin = ...
SD_CS: microcontroller.Pin = ...
POWER_EXT: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
IT8951_CS: microcontroller.Pin = ...
IT8951_RESET: microcontroller.Pin = ...
IT8951_POWER: microcontroller.Pin = ...
IT8951_BUSY: microcontroller.Pin = ...
PORTC_RX: microcontroller.Pin = ...
RX2: microcontroller.Pin = ...
D18: microcontroller.Pin = ...
PORTC_TX: microcontroller.Pin = ...
TX2: microcontroller.Pin = ...
D19: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
D21: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
D22: microcontroller.Pin = ...
PORTA_SDA: microcontroller.Pin = ...
D25: microcontroller.Pin = ...
PORTA_SCL: microcontroller.Pin = ...
D32: microcontroller.Pin = ...
PORTB_IN: microcontroller.Pin = ...
D26: microcontroller.Pin = ...
PORTB_OUT: microcontroller.Pin = ...
D33: microcontroller.Pin = ...
BATTERY_VOLTAGE: microcontroller.Pin = ...
TOUCH_INT: microcontroller.Pin = ...
BTN_UP: microcontroller.Pin = ...
BTN_CENTER: microcontroller.Pin = ...
BTN_DOWN: microcontroller.Pin = ...
PORTA_I2C: typing.Any = ...
DISPLAY: displayio.Display = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

