from __future__ import annotations
import busio
import displayio
import microcontroller
import typing
"""
board Adafruit Macropad RP2040
https://circuitpython.org/boards/adafruit_macropad_rp2040
"""
KEY1: microcontroller.Pin = ...
KEY2: microcontroller.Pin = ...
KEY3: microcontroller.Pin = ...
KEY4: microcontroller.Pin = ...
KEY5: microcontroller.Pin = ...
KEY6: microcontroller.Pin = ...
KEY7: microcontroller.Pin = ...
KEY8: microcontroller.Pin = ...
KEY9: microcontroller.Pin = ...
KEY10: microcontroller.Pin = ...
KEY11: microcontroller.Pin = ...
KEY12: microcontroller.Pin = ...
LED: microcontroller.Pin = ...
SPEAKER_ENABLE: microcontroller.Pin = ...
SPEAKER: microcontroller.Pin = ...
ENCODER_SWITCH: microcontroller.Pin = ...
BUTTON: microcontroller.Pin = ...
ENCODER_A: microcontroller.Pin = ...
ROTA: microcontroller.Pin = ...
ENCODER_B: microcontroller.Pin = ...
ROTB: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
OLED_CS: microcontroller.Pin = ...
OLED_RESET: microcontroller.Pin = ...
OLED_DC: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
DISPLAY: displayio.Display = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


