from __future__ import annotations
import microcontroller
"""
board 2231puppy E-Fidget
https://circuitpython.org/boards/e_fidget
"""
GP0: microcontroller.Pin = ...
GP1: microcontroller.Pin = ...
GP2: microcontroller.Pin = ...
BTN1: microcontroller.Pin = ...
BTN3: microcontroller.Pin = ...
BTN2: microcontroller.Pin = ...
M1: microcontroller.Pin = ...
M2: microcontroller.Pin = ...
M3: microcontroller.Pin = ...
M4: microcontroller.Pin = ...
M5: microcontroller.Pin = ...
M6: microcontroller.Pin = ...
M7: microcontroller.Pin = ...
M8: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
SMPS_MODE: microcontroller.Pin = ...
VBUS_SENSE: microcontroller.Pin = ...
GP26_A0: microcontroller.Pin = ...
GP26: microcontroller.Pin = ...
A0: microcontroller.Pin = ...
VOLTAGE_MONITOR: microcontroller.Pin = ...
