from __future__ import annotations
import busio
import microcontroller
"""
board NXP iMX RT 1020 EVK
https://circuitpython.org/boards/imxrt1020_evk
"""
AUDIO_INT: microcontroller.Pin = ...
AUDIO_SYNC: microcontroller.Pin = ...
AUDIO_BCLK: microcontroller.Pin = ...
AUDIO_RXD: microcontroller.Pin = ...
AUDIO_TXD: microcontroller.Pin = ...
AUDIO_MCLK: microcontroller.Pin = ...
ETHERNET_MDIO: microcontroller.Pin = ...
ETHERNET_MDC: microcontroller.Pin = ...
ETHERNET_RXD0: microcontroller.Pin = ...
ETHERNET_RXD1: microcontroller.Pin = ...
ETHERNET_CRS_DV: microcontroller.Pin = ...
ETHERNET_TXD0: microcontroller.Pin = ...
ETHERNET_TXD1: microcontroller.Pin = ...
ETHERNET_TXEN: microcontroller.Pin = ...
ETHERNET_INT: microcontroller.Pin = ...
ETHERNET_RST: microcontroller.Pin = ...
ETHERNET_CLK: microcontroller.Pin = ...
ETHERNET_RXER: microcontroller.Pin = ...
FREELINK_TX: microcontroller.Pin = ...
FREELINK_RX: microcontroller.Pin = ...
CAN_TX: microcontroller.Pin = ...
CAN_RX: microcontroller.Pin = ...
CAN_STBY: microcontroller.Pin = ...
ACCELEROMETER_SDA: microcontroller.Pin = ...
ACCELEROMETER_SCL: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

