from __future__ import annotations
import busio
import microcontroller
import typing
"""
board Czech maker ES3ink
https://circuitpython.org/boards/es3ink
"""
BUTTON: microcontroller.Pin = ...
IO0: microcontroller.Pin = ...
BOOT0: microcontroller.Pin = ...
IO1: microcontroller.Pin = ...
IO2: microcontroller.Pin = ...
VOLTAGE_MONITOR: microcontroller.Pin = ...
IO3: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
IO4: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
IO5: microcontroller.Pin = ...
EPD_RESET: microcontroller.Pin = ...
IO6: microcontroller.Pin = ...
EPD_BUSY: microcontroller.Pin = ...
IO7: microcontroller.Pin = ...
IO8: microcontroller.Pin = ...
NEOPIXEL_POWER: microcontroller.Pin = ...
IO9: microcontroller.Pin = ...
EPD_CS: microcontroller.Pin = ...
IO10: microcontroller.Pin = ...
EPD_DC: microcontroller.Pin = ...
IO11: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
IO12: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
IO13: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
IO14: microcontroller.Pin = ...
IO15: microcontroller.Pin = ...
IO16: microcontroller.Pin = ...
IO17: microcontroller.Pin = ...
IO18: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
IO19: microcontroller.Pin = ...
IO20: microcontroller.Pin = ...
IO21: microcontroller.Pin = ...
IO26: microcontroller.Pin = ...
IO33: microcontroller.Pin = ...
IO34: microcontroller.Pin = ...
IO35: microcontroller.Pin = ...
IO36: microcontroller.Pin = ...
IO37: microcontroller.Pin = ...
IO38: microcontroller.Pin = ...
IO39: microcontroller.Pin = ...
IO40: microcontroller.Pin = ...
IO41: microcontroller.Pin = ...
IO42: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
IO43: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
IO44: microcontroller.Pin = ...
IO45: microcontroller.Pin = ...
IO46: microcontroller.Pin = ...
IO47: microcontroller.Pin = ...
IO48: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

