from __future__ import annotations
import busio
import microcontroller
"""
board BDMICRO LLC VINA-D51
https://circuitpython.org/boards/bdmicro_vina_d51
"""
A0: microcontroller.Pin = ...
A1: microcontroller.Pin = ...
A10: microcontroller.Pin = ...
A11: microcontroller.Pin = ...
A2: microcontroller.Pin = ...
A3: microcontroller.Pin = ...
A4: microcontroller.Pin = ...
A5: microcontroller.Pin = ...
A6: microcontroller.Pin = ...
A7: microcontroller.Pin = ...
A8: microcontroller.Pin = ...
A9: microcontroller.Pin = ...
AUX_1: microcontroller.Pin = ...
AUX_UART_TX: microcontroller.Pin = ...
AUX_SPI_MOSI: microcontroller.Pin = ...
AUX_I2C_SDA: microcontroller.Pin = ...
ATW01_MOSI: microcontroller.Pin = ...
ESP01_TX: microcontroller.Pin = ...
AUX_10: microcontroller.Pin = ...
ATW01_IRQ: microcontroller.Pin = ...
AUX_11: microcontroller.Pin = ...
ATW01_GPIO_3: microcontroller.Pin = ...
AUX_12: microcontroller.Pin = ...
ATW01_GPIO_1: microcontroller.Pin = ...
AUX_3: microcontroller.Pin = ...
AUX_UART_RTS: microcontroller.Pin = ...
AUX_SPI_SS: microcontroller.Pin = ...
ATW01_SS: microcontroller.Pin = ...
ESP01_GPIO0: microcontroller.Pin = ...
AUX_4: microcontroller.Pin = ...
ATW01_RESET: microcontroller.Pin = ...
ESP01_RESET: microcontroller.Pin = ...
AUX_5: microcontroller.Pin = ...
AUX_UART_CTS: microcontroller.Pin = ...
AUX_SPI_MISO: microcontroller.Pin = ...
ATW01_MISO: microcontroller.Pin = ...
ESP01_GPIO2: microcontroller.Pin = ...
AUX_6: microcontroller.Pin = ...
ATW01_EN: microcontroller.Pin = ...
ESP01_CH_PD: microcontroller.Pin = ...
AUX_8: microcontroller.Pin = ...
AUX_UART_RX: microcontroller.Pin = ...
AUX_SPI_SCK: microcontroller.Pin = ...
AUX_I2C_SCL: microcontroller.Pin = ...
ATW01_SCK: microcontroller.Pin = ...
ESP01_RX: microcontroller.Pin = ...
AUX_9: microcontroller.Pin = ...
ATW01_WAKE: microcontroller.Pin = ...
D0: microcontroller.Pin = ...
D1: microcontroller.Pin = ...
D10: microcontroller.Pin = ...
D11: microcontroller.Pin = ...
D12: microcontroller.Pin = ...
D13: microcontroller.Pin = ...
D14: microcontroller.Pin = ...
D15: microcontroller.Pin = ...
I2S_SDO: microcontroller.Pin = ...
D16: microcontroller.Pin = ...
I2S_SDI: microcontroller.Pin = ...
D17: microcontroller.Pin = ...
I2S_FS_0: microcontroller.Pin = ...
D18: microcontroller.Pin = ...
I2S_SCK_0: microcontroller.Pin = ...
D19: microcontroller.Pin = ...
I2S_MCK_0: microcontroller.Pin = ...
D2: microcontroller.Pin = ...
D3: microcontroller.Pin = ...
D4: microcontroller.Pin = ...
D5: microcontroller.Pin = ...
D6: microcontroller.Pin = ...
D7: microcontroller.Pin = ...
D8: microcontroller.Pin = ...
D9: microcontroller.Pin = ...
DAC0: microcontroller.Pin = ...
DAC1: microcontroller.Pin = ...
I2C1_SCL: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
I2C1_SDA: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
LED_AUX: microcontroller.Pin = ...
LED_B: microcontroller.Pin = ...
LED_STATUS: microcontroller.Pin = ...
LED_G: microcontroller.Pin = ...
LED_QSPI: microcontroller.Pin = ...
LED_R: microcontroller.Pin = ...
LED_RX: microcontroller.Pin = ...
LED_TX: microcontroller.Pin = ...
RS485_RE: microcontroller.Pin = ...
RS485_RX: microcontroller.Pin = ...
RS485_TE: microcontroller.Pin = ...
RS485_TX: microcontroller.Pin = ...
SPI1_MISO: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
SPI1_MOSI: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
SPI1_SCK: microcontroller.Pin = ...
SCK: microcontroller.Pin = ...
SPI1_SS: microcontroller.Pin = ...
SS: microcontroller.Pin = ...
UART1_CTS: microcontroller.Pin = ...
UART1_RTS: microcontroller.Pin = ...
UART1_RX: microcontroller.Pin = ...
UART1_TX: microcontroller.Pin = ...
UART2_RX: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
I2C2_SCL: microcontroller.Pin = ...
UART2_TX: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
I2C2_SDA: microcontroller.Pin = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

