from __future__ import annotations
import busio
import microcontroller
"""
board maholli PyCubed
https://circuitpython.org/boards/pycubed_mram_v05
"""
SCK: microcontroller.Pin = ...
MOSI: microcontroller.Pin = ...
MISO: microcontroller.Pin = ...
SD_CS: microcontroller.Pin = ...
RELAY_A: microcontroller.Pin = ...
BURN1: microcontroller.Pin = ...
BURN2: microcontroller.Pin = ...
DAC0: microcontroller.Pin = ...
EN_RF: microcontroller.Pin = ...
AIN5: microcontroller.Pin = ...
BATTERY: microcontroller.Pin = ...
L1PROG: microcontroller.Pin = ...
CHRG: microcontroller.Pin = ...
PA16: microcontroller.Pin = ...
PA17: microcontroller.Pin = ...
VBUS_RST: microcontroller.Pin = ...
PA19: microcontroller.Pin = ...
PA20: microcontroller.Pin = ...
PA22: microcontroller.Pin = ...
PB16: microcontroller.Pin = ...
PB17: microcontroller.Pin = ...
PB22: microcontroller.Pin = ...
PB23: microcontroller.Pin = ...
RF1_RST: microcontroller.Pin = ...
RF1_CS: microcontroller.Pin = ...
RF1_IO4: microcontroller.Pin = ...
RF1_IO0: microcontroller.Pin = ...
RF2_IO0: microcontroller.Pin = ...
RF2_IO4: microcontroller.Pin = ...
RF2_CS: microcontroller.Pin = ...
RF2_RST: microcontroller.Pin = ...
EN_GPS: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
TX2: microcontroller.Pin = ...
RX2: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SCL2: microcontroller.Pin = ...
SDA2: microcontroller.Pin = ...
WDT_WDI: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def SPI() -> busio.SPI:
    """Returns the `busio.SPI` object for the board's designated SPI bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.SPI`.
    """
    ...


